### PR TITLE
Fix campaign builder source identifier regression

### LINKED ISSUE #15968: Creating a new campaign throws an exception
Tested on the 7.x branch

Steps to reproduce:
1. Create a segment
2. Create a campaign - select the segment and add the “Adjust contact points” action, then try to save
3. An exception is thrown

Image

```
[2026-03-18T17:13:16.931916+00:00] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\EntityNotFoundException: "Entity of type 'Mautic\LeadBundle\Entity\LeadList' for IDs id(test-segment) was not found" at /var/www/html/vendor/doctrine/orm/src/EntityNotFoundException.php line 33 {"exception":"[object] (Doctrine\\ORM\\EntityNotFoundException(code: 0): Entity of type 'Mautic\\LeadBundle\\Entity\\LeadList' for IDs id(test-segment) was not found at /var/www/html/vendor/doctrine/orm/src/EntityNotFoundException.php:33)
[stacktrace]
#0 /var/www/html/vendor/doctrine/orm/src/Proxy/ProxyFactory.php(351): Doctrine\\ORM\\EntityNotFoundException::fromClassNameAndIdentifier()
#1 /var/www/html/var/cache/dev/doctrine/orm/Proxies/__CG__MauticLeadBundleEntityLeadList.php(225): Doctrine\\ORM\\Proxy\\ProxyFactory->{closure:Doctrine\\ORM\\Proxy\\ProxyFactory::createInitializer():309}()
#2 /var/www/html/var/cache/dev/doctrine/orm/Proxies/__CG__MauticLeadBundleEntityLeadList.php(225): Closure->__invoke()
#3 /var/www/html/app/bundles/CampaignBundle/Entity/Campaign.php(605): Proxies\\__CG__\\Mautic\\LeadBundle\\Entity\\LeadList->getName()
#4 /var/www/html/app/bundles/CampaignBundle/Model/CampaignModel.php(465): Mautic\\CampaignBundle\\Entity\\Campaign->addList()
#5 /var/www/html/app/bundles/CampaignBundle/Controller/CampaignController.php(789): Mautic\\CampaignBundle\\Model\\CampaignModel->setLeadSources()
#6 /var/www/html/app/bundles/CampaignBundle/Controller/CampaignController.php(470): Mautic\\CampaignBundle\\Controller\\CampaignController->beforeEntitySave()
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(183): Mautic\\CampaignBundle\\Controller\\CampaignController->newAction()
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#9 /var/www/html/vendor/symfony/framework-bundle/Controller/AbstractController.php(122): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#10 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(435): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->forward()
#11 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(183): Mautic\\CoreBundle\\Controller\\CommonController->executeAction()
#12 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#13 /var/www/html/vendor/symfony/http-kernel/Kernel.php(193): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#14 /var/www/html/app/AppKernel.php(101): Symfony\\Component\\HttpKernel\\Kernel->handle()
#15 /var/www/html/app/middlewares/CORSMiddleware.php(76): AppKernel->handle()
#16 /var/www/html/app/middlewares/HSTSMiddleware.php(39): Mautic\\Middleware\\CORSMiddleware->handle()
#17 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(28): Mautic\\Middleware\\HSTSMiddleware->handle()
#18 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle()
#19 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle()
#20 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle()
#21 /var/www/html/app/middlewares/StackedHttpKernel.php(55): Mautic\\Middleware\\TrustMiddleware->handle()
#22 /var/www/html/index.php(19): Mautic\\Middleware\\StackedHttpKernel->handle()
#23 {main}
"} {"hostname":"mautic-web","pid":1899}

```

_Originally posted by @matbcvo in https://github.com/mautic/mautic/issues/15721#issuecomment-4081615251_
            

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ✔️
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | No issue created

## Description

This fixes a regression in campaign builder source handling that can cause campaign saves to fail with a 500 error.

The regression was introduced in PR #15598 (`0cff037b7b`, from `kniziol/bugfix/quick-filters-for-segments-and-emails-15494`), where campaign list source choices were changed from numeric segment ids to segment aliases. That changed the submitted source identifier shape, but the persistence path was not updated accordingly.

As a result:

- campaign source forms could submit segment aliases such as `list-one`
- source data was carried through the builder as keyed maps in `modifiedSources`
- `$this->campaignSources`, `$this->addedSources`, and `$this->deletedSources` could keep those non-normalized identifiers
- `CampaignModel::setLeadSources()` still treated source keys as `LeadList` primary keys
- Doctrine then tried to load a segment using the alias as an id and threw an `EntityNotFoundException`

A later change in PR #15721 updated tests to follow the alias-based behavior, which helped mask the underlying contract mismatch instead of catching it.

This PR fixes the issue cleanly by normalizing campaign source identifiers end to end:

- campaign list source choices now use numeric segment ids
- submitted source maps are built as explicit keyed lookup maps instead of positional `array_flip()` output
- controller source state is normalized before diffing, so `campaignSources`, `addedSources`, and `deletedSources` are consistently id-keyed
- persistence resolves only normalized numeric source identifiers

This restores a consistent contract from Symfony form submission through builder state and controller diffing into campaign source persistence.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Start Mautic and log in.
3. Open Campaigns and create a new campaign in the builder.
4. Add a segment source and at least one event/action.
5. Save the campaign from the builder.
6. Confirm the campaign saves successfully and no 500 error is returned.
7. Reload the campaign and confirm the selected segment source is still shown correctly.
8. Edit the campaign source selection, add or remove a segment source, and save again.
9. Confirm source additions and removals are persisted correctly.
10. If reproducing from an intercepted request, submit a payload that previously contained a segment alias such as `list-one` in `modifiedSources.lists` and confirm the save no longer crashes.

### CODE REVIEW

File: app/bundles/CampaignBundle/Tests/CampaignTestAbstract.php [hunk 1]
```diff
@@ -25,10 +26,13 @@ class CampaignTestAbstract extends TestCase
     protected static int $mockId       = 232;
     protected static string $mockName  = 'Mock name';
     protected static string $mockAlias = 'Mock alias';
+    /** @var EntityManager&MockObject */
+    protected EntityManager $entityManager;
```
Comment (escopecz) [inline app/bundles/CampaignBundle/Tests/CampaignTestAbstract.php:30]:
```suggestion
    protected EntityManagerInterface&MockObject $entityManager;
```

File: app/bundles/CampaignBundle/Model/CampaignModel.php [hunk 2]
```diff
@@ -489,6 +501,28 @@ public function setLeadSources(Campaign $entity, $addedSources, $deletedSources)
         }
     }
 
+    private function getLeadListSource(int|string $identifier): ?LeadList
+    {
+        if (!ctype_digit((string) $identifier)) {
+            return null;
+        }
+
+        $list = $this->em->find(LeadList::class, (int) $identifier);
```
Comment (escopecz) [inline app/bundles/CampaignBundle/Model/CampaignModel.php:510]: Can we keep using `$entity->addList($this->em->getReference(LeadList::class, (int) $id));` to save the DB query?

File: app/bundles/CampaignBundle/Model/CampaignModel.php [hunk 3]
```diff
@@ -506,7 +540,7 @@ public function getSourceLists($sourceType = null, $globalOnly = false): array
 
                 if ($lists) {
                     foreach ($lists as $list) {
-                        $choices['lists'][$list['alias']] = $list['name'];
+                        $choices['lists'][$list['id']] = $list['name'];
```
Comment (escopecz) [inline app/bundles/CampaignBundle/Model/CampaignModel.php]: This is the ultimate fix, right? Basically reverting https://github.com/mautic/mautic/pull/15598. Do we need all the other changes that are checking if the ID is a number?

File: app/bundles/CampaignBundle/Model/CampaignModel.php (hunk 2 above)
Comment (shinde-rahul) [reply app/bundles/CampaignBundle/Model/CampaignModel.php:510]: I agree in general, but in this path `getReference()` does not really avoid the query.

`Campaign::addList()` / `Campaign::removeList()` immediately call `getId()` and `getName()` on the `LeadList`, so the proxy is initialized right away. Because of that, `getReference()` would only defer the lookup, not eliminate it.

I kept `find()` here so invalid or stale ids can be ignored safely instead of failing later through proxy initialization.

File: app/bundles/CampaignBundle/Model/CampaignModel.php (hunk 3 above)
Comment (shinde-rahul) [reply app/bundles/CampaignBundle/Model/CampaignModel.php]: I checked `#15598` more closely. I don’t think we should revert it globally.

That PR changed shared “More” filter values to prefer aliases, which is appropriate for search/filter flows. The regression here is narrower: campaign builder persistence still expects numeric source ids, but the builder path started receiving alias-based values.

So the fix I’m aiming for is:
- keep alias-based values for quick-filter/search flows introduced by #15598 (I have pushed this [commit](https://github.com/mautic/mautic/pull/15987/commits/cb7438a72067b7d4e2963ecf814f9a8b16d45b1f))
- use numeric ids only in the builder/persistence path where campaign sources are saved

The `ctype_digit()` checks are mostly hardening. They are not the core fix, but they protect against stale or malformed `campaignSources` / `modifiedSources` payloads coming back from browser state, so invalid keys are ignored instead of reaching persistence.

One more thing I observed while checking this: the email `list:<alias>` path appears incomplete in current code, because EmailRepository.php does not natively support a list search command. So the email filter behavior should be treated separately from this campaign fix, not as a reason to revert the campaign change globally.

File: app/bundles/CampaignBundle/Model/CampaignModel.php (hunk 2 above)
Comment (escopecz) [reply app/bundles/CampaignBundle/Model/CampaignModel.php:510]: That's fair. It won't fix some race conditions but it could reduce them.

File: app/bundles/CampaignBundle/Model/CampaignModel.php (hunk 3 above)
Comment (escopecz) [reply app/bundles/CampaignBundle/Model/CampaignModel.php]: Clear. Thanks!

**Comment by escopecz** [comment]
@shinde-rahul I tested the steps from https://github.com/mautic/mautic/pull/15598 with email segment filter and it didn't work. I'd rather fix the campaigns and leave the email filter broken but do you think we could not break it?

I'll merge this today no matter what. A broken filter is nothing compared to broken campaigns.

**Review by escopecz — APPROVED** [review]
Approving as this fixes the regression that is blocking the release of M7.1 and testing of other PRs.

**Comment by shinde-rahul** [comment]
> @shinde-rahul I tested the steps from #15598 with email segment filter and it didn't work. I'd rather fix the campaigns and leave the email filter broken but do you think we could not break it?
> 
> I'll merge this today no matter what. A broken filter is nothing compared to broken campaigns.

@escopecz, here is the fix https://github.com/mautic/mautic/pull/16027.
