### PR TITLE
Fix yes/no button for emails

### LINKED ISSUE #10231: Error in API Library tests relating to GrapesJS builder
## Bug Description
The API library tests have been failing since 25th June with the following error:

`Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuil...`

See full run details here: https://github.com/mautic/api-library/runs/2989055129?check_suite_focus=true

### PR DESCRIPTION
**Pull request by kuzmany**
closes https://github.com/mautic/mautic/pull/10259
closes #10231 

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #10231 

#### Description:
Switch active/not active email not work on emails list

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to emails
3. Try switch off/on
4. See the error
5. After PR should work properly

### CODE REVIEW

**Comment by kuzmany** [comment]
@fedys do you have idea why CS fixer fail?

**Comment by fedys** [comment]
@kuzmany That's strange. On these [lines](https://github.com/mautic/mautic/blob/bf39ccbdfe1ef3403db59773c100480ee9028f98/.github/workflows/tests.yml#L149-L150) there is no `--git` flag. The only thing I can think of is that `$(git diff -- '*.php' --name-only --diff-filter=ACMRTUXB "HEAD~..HEAD")` could produce `--git` somehow which is also strange 🤔

**Comment by fedys** [comment]
@kuzmany try changing it to something like
```
bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --show-progress=dots \
--diff app/bundles/LeadBundle/Controller/Api/CompanyApiController.php
```
to see if the problem is in `$(git diff -- '*.php' --name-only --diff-filter=ACMRTUXB "HEAD~..HEAD")`

**Comment by RCheesley** [comment]
This did not address the issue for me. I am still seeing the error when switching the emails on/off.

Here's a screencast to demonstrate, with the PR being applied and GrapesJS being enabled as the builder.

https://youtu.be/h6DbKhFJ5K8

**Comment by fedys** [comment]
@kuzmany cs-fixer issue fixed in a8d6199.

**Comment by fedys** [comment]
@kuzmany once https://github.com/mautic/mautic/pull/10059 is merged into `features` you should revert my a8d6199 and rebase onto `features`. There were several issues with `CS Fixer` GitHub Action so I created a separate PR.

**Comment by RCheesley** [comment]
@kuzmany a small conflict to address here - is this still an issue with Mautic 4?

**Comment by RCheesley** [comment]
@kuzmany per [@fedys 's comment](https://github.com/mautic/mautic/pull/10023#issuecomment-844082273), can you please revert the commit and rebase on features? Thanks! :)

**Comment by kuzmany** [comment]
@RCheesley done

**Review by dennisameling — DISMISSED** [review]
Can confirm this fixes the API library issues as well 🚀  https://github.com/mautic/api-library/runs/3068060332?check_suite_focus=true - code looks good to me.
 
Thanks @kuzmany!

Just needs someone to test the PR from the user perspective, as described in the PR description. CC @RCheesley

**Review by luguenth — DISMISSED** [review]
The PR works flawlessly for me. Good Job :rocket:

**Comment by RCheesley** [comment]
@kuzmany looks like this needs a [tweak to the test coverage](https://app.codecov.io/gh/mautic/mautic/compare/10023/diff#diff-cGx1Z2lucy9HcmFwZXNKc0J1aWxkZXJCdW5kbGUvTW9kZWwvR3JhcGVzSnNCdWlsZGVyTW9kZWwucGhw) before we are able to merge it - can you have a quick look?

File: plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php [hunk 1]
```diff
@@ -66,13 +60,13 @@ public function addOrEditEntity(Email $email)
...
             }
-        }
 
-        $this->getRepository()->saveEntity($grapesJsBuilder);
+            $this->getRepository()->saveEntity($grapesJsBuilder);
 
-        $customHtml = ArrayHelper::getValue('customHtml', $this->requestStack->getCurrentRequest()->get('emailform'));
-        $email->setCustomHtml($customHtml);
-        $this->emailModel->getRepository()->saveEntity($email);
+            $customHtml = $this->requestStack->getCurrentRequest()->get('emailform')['customHtml'] ?? null;
```
Comment (escopecz) [inline plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php:66]: @Enc3phale I'm not sure about this. Are we sure that the `customHtml` will be always in the request? If it won't be then it will set the customHtml of the email to null.

Comment (kuzmany) [reply plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php:66]: This assume check  this->requestStack->getCurrentRequest()->request->has('grapesjsbuilder') https://github.com/kuzmany/mautic/blob/fix-yes-no-switch/plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php#L57

Then If grapesjsbuilder is in the requests, we assume request is from create/edit page

Comment (escopecz) [reply plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php:66]: Ok, let's hope it is true 👍

**Review by escopecz — APPROVED** [review]
👍

**Comment by RCheesley** [comment]
@escopecz are we good to merge this now, or did we need to fix some other stuff before we do that?

**Comment by RCheesley** [comment]
@all-contributors please add @escopecz for Tests
