### PR TITLE
fix: [DPMMA-3098] fix report data bool filter

### LINKED ISSUE #14857: Bug: "Is Published" filter in Reports doesn't allow selecting "True" or "False"
### Description

When creating or editing a Report and trying to use the **Is published** filter, the dropdown only shows operators like "equal" and "not equal", but there's no option to choose true or false as values.

### Steps to Reproduce:

- Go to Reports and click "New" or edit an existing report.
- In the Data tab, add a filter.
- Choose the **Is published** column.
- Observe that while "equal" / "not equal" are available, there's no dropdown or input for selecting true or false.

------ 
Screenshot 2025-04-07 at 10 29 38
Can't choose true and the dropdown just allow "equal" or "not equal". And I can't add that report to the Dashboard.

_Originally posted by @Bastian2718 in https://github.com/mautic/mautic/issues/14827#issuecomment-2782475384_

### PR DESCRIPTION
**Pull request by AlanWierzchonCA**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️ 
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ❌ 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Fix for Issue: https://github.com/mautic/mautic/issues/14857
**Bug: "Is Published" filter in Reports doesn't allow selecting "True" or "False"**

---
### 📋 Steps to test this PR:

1. Go to Reports and click "New" or edit an existing report.
2. In the Data tab, add a filter.
3. Choose the Is published column.
4. Observe that while "equal" / "not equal" are available, there's no dropdown or input for selecting true or false.

### CODE REVIEW

**Comment by patrykgruszka** [comment]
Can you rebase this onto the 5.2 branch? We should have this fix in that version.

**Comment by matbcvo** [comment]
@AlanWierzchonCA, just a heads-up, it needs to be rebased onto [the 5.2 branch](https://github.com/mautic/mautic/tree/5.2), not 5.x. The 5.x branch is locked and doesn’t accept any PRs. We'll merge it into the 6.0 and 7.x branches later.

**Comment by AlanWierzchonCA** [comment]
@patrykgruszka @matbcvo rebased this onto the 5.2 branch

**Comment by matbcvo** [comment]
This fix makes the boolean appear, but there’s another issue - the boolean value is not being saved. I checked the database and confirmed that the boolean value is not being saved or updated. For example, the "Dynamic?" boolean works correctly.

https://github.com/user-attachments/assets/b4b881bd-7fda-4afb-b482-90c31b7911ad

**Comment by Hugo-Prossaird** [comment]
I have tested this PR locally, and everything works correctly with the latest commit ✅

**Review by kuzmany — APPROVED** [review]
Faced the same issue. And this fixed it 👍

**Review by kingsedem — APPROVED** [review]
Tested and works as expected

image

**Review by patrykgruszka — CHANGES_REQUESTED** [review]
This approach will cause ID conflicts, I would suggest to try with something like this:
```
if (filterType == 'bool' || filterType == 'boolean') {
  const yesId = valueId + '_1';
  const noId = valueId + '_0';
  const isYes = valueVal == '1';
  const $template = mQuery(mQuery('#filterValueYesNoTemplate').html());
  const $label = $template.find('#report_value_template_yesno_label');
  const $yesOption = $template.find('#report_value_template_yesno_1');
  const $noOption = $template.find('#report_value_template_yesno_0');

  $yesOption.attr('name', valueName)
    .attr('id', yesId);
  $noOption.attr('name', valueName)
    .attr('id', noId);
  $label.attr('id', valueId + '_bool-label')
    .attr('data-yes-id', yesId)
    .attr('data-no-id', noId);

  mQuery(valueEl).replaceWith($template);

  if (!isYes) {
    Mautic.toggleYesNo($label);
  }
} else if // ....
```

**Comment by AlanWierzchonCA** [comment]
@kuzmany , @matbcvo I made changes as suggested by  @patrykgruszka

File: app/bundles/ReportBundle/Assets/js/report.js [hunk 1]
```diff
@@ -216,18 +216,26 @@ Mautic.updateReportFilterValueInput = function (filterColumn, setup) {
...
-            });
-            mQuery(valueEl).replaceWith(template);
-        }
-
-        if (setup) {
-            mQuery('#' + valueId + '_' + valueVal).click();
+        const yesId = valueId + '_1';
+        const noId = valueId + '_0';
+        const isYes = valueVal == '1';
+        const $template = mQuery('#filterValueYesNoTemplate');
```
Comment (patrykgruszka) [inline app/bundles/ReportBundle/Assets/js/report.js]:
```suggestion
        const $template = mQuery('#filterValueYesNoTemplate').clone();
        $template.attr('id', valueId + '_bool-container');
```
This is causing problem with creating the new filter element.

**Review by patrykgruszka — APPROVED** [review]
Looks fine now, thanks!

**Review by shinde-rahul — APPROVED** [review]
The code changes look good

**Comment by shinde-rahul** [comment]
Once this change is applied, I can toggle the boolean for the **isPublished** column under filters.

image
