### PR TITLE
Fix issue #14457: Contact names with ampersands not showing in search

### LINKED ISSUE #14457: Global Search Does Not Yield Results for Entries with Ampersands in Name/Title/First Name or custom Fields
### Mautic Series

6.0.x series

### Mautic installed version

6.x

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.3.14

### What browsers are you seeing the problem on?

_No response_

### What happened?

During a global search in Mautic, entries with ampersands (&) in fields like title, name, or company name do not return results. This issue occurs because the InputHelper::clean method encodes the ampersand into &#38;, causing a mismatch during the search.

### How can we reproduce this issue?

Step 1: Create a contact or company with the name R&D.
Step 2: Assign the contact or company R&D to a contact.
Step 3: Use the global search bar to search for R&D.
Step 4: Observe that no results are returned.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by goma101**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️ 
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ✔️ 
| Related user documentation PR URL      | N/A 
| Related developer documentation PR URL | N/A 
| Issue(s) addressed                     | Fixes #14457 

## Description

This PR fixes an issue where a global search would not return contacts (or other entities) with ampersands in one of their fields such as their names, if searched with the ampersand. This bug occurred because the `InputHelper::clean` method encodes characters such as ampersand into html encoding, thus causing a mismatch when executing a global search.

This fix decodes search strings before global search execution, thereby eliminating this mismatch and yielding correct results. The PR also includes a phpunit test, for the search example provided in the issue (Global search for Contact with name "R&D"), asserting the search is successful.

| Before                                 | After
| -------------------------------------- | ---
| before | after

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a contact or other entity with "&" in one of its fields
3. Execute a global search for the contact/entity by that field, **including the &** in the search
4. Confirm that the results are correct.

### CODE REVIEW

**Review by patrykgruszka — CHANGES_REQUESTED** [review]
I suggest removing the `InputHelper::clean` in the controller instead of decoding the query in every subscriber.

**Comment by goma101** [comment]
@patrykgruszka Indeed much more sensical, my bad.

Please tell me if it needs anything else, or if you'd like me to squash or something.

File: app/bundles/LeadBundle/Tests/Functional/SearchTestHelper.php [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+namespace Mautic\LeadBundle\Tests\Functional;
+
+use Mautic\CoreBundle\Test\MauticMysqlTestCase;
+use Mautic\LeadBundle\Entity\Lead;
+use Mautic\LeadBundle\Model\LeadModel;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpFoundation\Response;
+
+abstract class SearchTestHelper extends MauticMysqlTestCase
```
Comment (patrykgruszka) [inline app/bundles/LeadBundle/Tests/Functional/SearchTestHelper.php]:
```suggestion
abstract class AbstractSearchTest extends MauticMysqlTestCase
```

To maintain consistency, we should adjust the class name. Helper classes should be used as dependencies rather than abstract classes.

There are two options:
Option 1: Rename the class to something like `AbstractSearchTest` and it should be fine
Option 2: Modify it to function as a helper, similar to `app/bundles/EmailBundle/Tests/Functional/Fixtures/EmailFixturesHelper.php`.

Comment (goma101) [reply app/bundles/LeadBundle/Tests/Functional/SearchTestHelper.php]: I'll rename, and if you agree, I think it would also be better for extensibility to move the remaining search-related auxiliary functions in `SearchWithCustomFieldDataFunctionalTest.php` to the abstract.

Comment (patrykgruszka) [reply app/bundles/LeadBundle/Tests/Functional/SearchTestHelper.php]: Looks good!

**Review by patrykgruszka — APPROVED** [review]
The code looks fine and fixes the problem :+1: 
image

**Review by escopecz — APPROVED** [review]
I also believe that removing `InputHelper::clean` in this case is the right way to solve this 👍

**Comment by matbcvo** [comment]
@all-contributors please add @goma101 for code test
