### PR TITLE
Removing Merge button from Add New Company View

### LINKED ISSUE #13416: [UX] Redundant “New” button in Companies Merge modal
The “New” button in the Companies Merge modal currently leads to additional menu options that show without content. 
How to reproduce the bug:
1. Open Companies
2. Click to create a new
3. Fill any information
4. Click to merge
5. The wrong modal is displayed

Image

### Impact
It would eliminate unnecessary confusion caused by empty menu options and streamline the process of merging companies. It not only disrupts the workflow but also gives an impression of incomplete or faulty features.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by nishant-s7**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #13416  

#### Description:

This PR removes the redundant **Merge** button when creating a new company, which makes sure the incorrect modal with "New" button (as mentioned in the issue) is not displayed.
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to `Companies` and click on `New`.
3. In the top-right toolbar, verify that the `Merge` button is not displayed when creating a new company, but, it is visible once the company is saved, showing the correct modal on clicking it.

### CODE REVIEW

**Review by andersonjeccel — APPROVED** [review]
Thanks for fixing this! 👍🏻

**Review by shinde-rahul — APPROVED** [review]

File: app/bundles/LeadBundle/Controller/CompanyController.php [hunk 1]
```diff
@@ -209,7 +209,7 @@ public function newAction(Request $request, $entity = null)
         $leadFieldModel = $this->getModel('lead.field');
         \assert($leadFieldModel instanceof FieldModel);
         $fields = $leadFieldModel->getPublishedFieldArrays('company');
-        $form   = $model->createForm($entity, $this->formFactory, $action, ['fields' => $fields, 'update_select' => $updateSelect]);
+        $form   = $model->createForm($entity, $this->formFactory, $action, ['fields' => $fields, 'update_select' => $updateSelect, 'hide_extra_buttons' => true]);
```
Comment (escopecz) [inline app/bundles/LeadBundle/Controller/CompanyController.php]: 1. Let's call it what it really does.
2. Let's avoid double negatives as those are hard to comprehend and break my brain (like hide = false) 
```suggestion
        $form   = $model->createForm($entity, $this->formFactory, $action, ['fields' => $fields, 'update_select' => $updateSelect, 'show_merge_button' => false]);
```
Or, perhaps we could avoid this extra config option altogether if we'd base the condition if the company ID exists or not?

**Review by escopecz — CHANGES_REQUESTED** [review]

File: app/bundles/LeadBundle/Controller/CompanyController.php (hunk 1 above)
Comment (nishant-s7) [reply app/bundles/LeadBundle/Controller/CompanyController.php]: Yes! I'll do the change

**Review by shinde-rahul — CHANGES_REQUESTED** [review]
@nishant-s7 Please add PHPUnit tests for this change.

Ref: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#writing-tests

File: app/bundles/LeadBundle/Form/Type/CompanyType.php [hunk 2]
```diff
@@ -90,32 +90,40 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
...
-                            'data-header' => $this->translator->trans('mautic.lead.company.header.merge'),
-                            'href'        => $this->router->generate(
-                                'mautic_company_action',
-                                [
-                                    'objectId'     => $options['data']->getId(),
-                                    'objectAction' => 'merge',
-                                ]
-                            ),
+
+        if (null === $options['data']->id) {
```
Comment (escopecz) [inline app/bundles/LeadBundle/Form/Type/CompanyType.php]: Are you sure this will work? On the line 117 I can see it's accessed as `$options['data']->getId()`

Comment (nishant-s7) [reply app/bundles/LeadBundle/Form/Type/CompanyType.php]: It did work when I logged it, I also checked for the expected behavior and it worked fine. Should I change it to `getId()` to be on the safer side?

**Review by kuzmany — DISMISSED** [review]
Works for me 👍

File: app/bundles/LeadBundle/Form/Type/CompanyType.php (hunk 2 above)
Comment (escopecz) [reply app/bundles/LeadBundle/Form/Type/CompanyType.php]: There is some Twig magic where it looks if the property exists, if not it tries if `getId()` exists and if so it will use that. I'd prefer to use directly the entity method than the magic.
```suggestion
        if (null === $options['data']->getId()) {
```

**Review by escopecz — APPROVED** [review]
Works 👍  Thank you!
