### PR TITLE
Fix an issue with the "More" Quick Filters in Segments and Emails

### LINKED ISSUE #15494: Quick Filters "More" not working for Segments and Emails
### Mautic Series

7.0.x series

### Mautic installed version

7 alpha

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.4.10

### What browsers are you seeing the problem on?

_No response_

### What happened?

For Segments: 
When using the quick filter for "categories", the category ID is used (instead of the category alias) and thus never finds any matches.

For Email: 
When using the quick filter for "themes" or "segment" there are no results at all.

### How can we reproduce this issue?

For Segments
Step 1: Create a segment with a category
Step 2: Use the quick filter and choose your category from 1) 
Step 3: See no results 

For Email: 
Step 1: Create a segment email 
Step 2: Use the quick filter and choose your segment from 1) (alternatively filter on the theme you used)
Step 3: See no results

### Relevant log output

```shell
-
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by kniziol**
# Summary

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ✔️
| Related user documentation PR URL      | n/a
| Related developer documentation PR URL | n/a
| Issue(s) addressed                     | Fixes #15494

# Description
Looks like there is a discrepancy with the "More" Quick Filters:
- the selected filter contains `id`
- when building the "where" clause for SQL query, expected is `alias` (instead of `id`)

# 📋 Steps to test this PR

## For Segments
1. Create a segment with a category
2. Use the quick filter and choose your category from 1)
3. See no results

## For Email
1. Create a segment email
2. Use the quick filter and choose your segment from 1) (alternatively filter on the theme you used)
3. See no results

### CODE REVIEW

**Comment by escopecz** [comment]
@kniziol this is working for the segment filters:
Screenshot 2025-11-13 at 19 18 02

But not for the email filter:
Screenshot 2025-11-13 at 19 19 05

Do you think you could look into the email filters once more? I'm happy to merge this as is, but it fixes only half of the problem that is described in the description.

**Comment by kniziol** [comment]
> Do you think you could look into the email filters once more? I'm happy to merge this as is, but it fixes only half of the problem that is described in the description.

@escopecz Sure, let me check that

**Comment by kniziol** [comment]
> But not for the email filter: Screenshot 2025-11-13 at 19 19 05

| We can filter by `category`: | But cannot filter by `list` (there is no such filter): |
| - | - |
| Screenshot 2025-11-16 at 20 08 35 | Screenshot 2025-11-16 at 20 08 43 |

@escopecz Please let me know how to reproduce the issue in the `Emails` module.

**Comment by escopecz** [comment]
@kniziol this is what I did:

https://github.com/user-attachments/assets/968a3b82-c384-4c6e-8e94-15bedeaaf90a



cc @andersonjeccel

**Comment by kniziol** [comment]
@escopecz I’ve updated the filter functionality. Could you please take a look and confirm that everything is working as expected?

Here's how it works and looks on my end 👇

https://github.com/user-attachments/assets/54c9a692-0be5-4a87-b490-a1e6cc3b9f54

**Comment by escopecz** [comment]
@kniziol do you need help with the failing tests?

**Comment by kniziol** [comment]
@escopecz I’ve fixed all the failing tests. Please approve the PR.

**Review by escopecz — APPROVED** [review]
Looks good 👍

**Review by matbcvo — APPROVED** [review]
Tested the PR, found no issues

File: app/bundles/CampaignBundle/Model/CampaignModel.php [hunk 1]
```diff
@@ -500,7 +506,7 @@ public function getSourceLists($sourceType = null, $globalOnly = false): array
 
                 if ($lists) {
                     foreach ($lists as $list) {
-                        $choices['lists'][$list['id']] = $list['name'];
+                        $choices['lists'][$list['alias']] = $list['name'];
```
Comment (escopecz) [inline app/bundles/CampaignBundle/Model/CampaignModel.php:509]: @kniziol I believe this broke campaigns. Can you please take a look? 

See https://github.com/mautic/mautic/issues/15968

Comment (kniziol) [reply app/bundles/CampaignBundle/Model/CampaignModel.php:509]: Sure, I checked that and couldn’t reproduce the issue. I’ve attached a video 👉 https://github.com/mautic/mautic/issues/15968#issuecomment-4143137935.
