### PR TITLE
Validate trusted hosts config variable.

### LINKED ISSUE #15743: Trusted Hosts setting accepts plain hostnames but requires regex, causing complete site lockout
### Mautic Series

6.0.x series

### Mautic installed version

6.0.7

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.3.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

1. The "Trusted Hosts" configuration field in System Settings accepts plain hostname input (e.g., cricketstadium.nyc) without validation or conversion, but Symfony's trusted_hosts feature requires regex patterns. This causes an immediate and complete site lockout with no way to recover through the UI.

### How can we reproduce this issue?

**Steps to Reproduce:**

1. Go to Settings → Configuration → System Settings
2. Enter a plain hostname in "Trusted Hosts" field (e.g., domain.com)
3. Save the configuration
4. Attempt to access any page on the site

**Expected Behavior:**
Either:

- The input should be validated/converted to a proper regex pattern (e.g., ^domain\.com$)
- The UI should display a warning that regex format is required
- Documentation/placeholder text should indicate the expected format

**Actual Behavior:**

- The value is saved with a trailing slash appended (domain.com/)
- The site immediately returns BadRequestHttpException: Untrusted Host
- User is completely locked out with no UI access to fix the setting
- Manual database or config file edit is required to recover

**Suggested Fix:**

1. Remove the trailing slash being appended to the input
2. Either auto-escape dots and anchor the pattern, or validate that input is valid regex
3. Add placeholder text showing expected format (e.g., ^example\.com$)
4. Consider a confirmation dialog warning about potential lockout

### Relevant log output

```shell
Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: 
"Untrusted Host "domain.com"." at vendor/symfony/http-kernel/HttpKernel.php line 83
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️ 
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ✔️ 
| Issue(s) addressed                     | Fixes #15743  

## Description
Validate trusted hosts config variable.
Add a "Caution" to help text.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to Settings → Configuration → System Settings
3. Enter invalid regexp in "Trusted Hosts" "trusted.com/"
4. Check error message on the field.
5. Enter invalid domain in "Trusted Hosts" "trusted..com"
6. Check error message on the field.
7. Enter valid trusted host or regexp.
8. Check the page still loads.

### CODE REVIEW

**Comment by escopecz** [comment]
@biozshock when I test with value `mautic-community.ddev.site/` I get this error after config save:
```
500 Internal Server Error - PHP Warning - preg_match(): Unknown modifier '/' 
Mautibot
[Report an issue](http://mau.tc/report-issue)
ErrorException
/html/app/bundles/CoreBundle/Form/Type/ConfigType.php:220 at
Mautic\CoreBundle\ErrorHandler\ErrorHandler -> handleError ( )
```
I think I was able to reproduce the issue before applying this patch. I got
Screenshot 2026-04-01 at 11 45 16

Is that what this PR is fixing?

**Comment by biozshock** [comment]
@escopecz  If you check the `ConfigType` file on the line 220 you'd see the silencing operator https://github.com/mautic/mautic/pull/16006/changes#diff-7c0dfd3c43701ab65aaf5dd7b37a7edc52fe077939f0aceab8ef6cd24e6fad5eR220. Maybe your environment forbids silencing?

File: app/bundles/CoreBundle/Form/Type/ConfigType.php [hunk 1]
```diff
@@ -202,8 +202,37 @@ public function buildForm(FormBuilderInterface $builder, array $options): void
...
+                            }
+
+                            if ([] === $values) {
+                                return;
+                            }
+
+                            foreach ($values as $value) {
+                                if (str_contains($value, '*') || str_contains($value, '/') || str_contains($value, '\\') || str_contains($value, '?') || str_contains($value, '^') || str_contains($value, '$')) {
+                                    // Regexp given
+                                    if (false === @preg_match('/'.$value.'/', '')) {
```
Comment (escopecz) [inline app/bundles/CoreBundle/Form/Type/ConfigType.php]: Shouldn't we quote the value to avoid this issue?
```suggestion
                                    if (false === @preg_match('/'.preg_quote($value, '/').'/', '')) {
```

Comment (biozshock) [reply app/bundles/CoreBundle/Form/Type/ConfigType.php]: Nope, that way you'd quote in a `preg_match` an invalid regexp like you posted above: `mautic-community.ddev.site/`.
The PR requires the user to enter a properly quoted regexp or a domain names.

Comment (biozshock) [reply app/bundles/CoreBundle/Form/Type/ConfigType.php]: Changed help text to reflect requirements.

**Comment by biozshock** [comment]
@escopecz Added some tests to cover explicit check for trailing slash.

File: app/bundles/CoreBundle/Form/Type/ConfigType.php (hunk 1 above)
Comment (biozshock) [reply app/bundles/CoreBundle/Form/Type/ConfigType.php]: BTW, could use `Nette\Utils\Strings::match`, but that's introducing yet another dependency for sake of validating regexp more clearly.

**Comment by escopecz** [comment]
I'm still getting the error. Testing with debug on. I'm thinking whether we could try a different modifier that isn't used much in domains. `/` is way more possible than `'` for example.

But the good thing is that when the error happens it won't kill the whole Mautic. It won't save the config form. So I can refresh and try again.

**Comment by biozshock** [comment]
@escopecz I've added the case into tests. Can you please check if the case is on on your local? Can't think of a setup that will not allow a silence operator.

If one would use `/` in domain name that would be an invalid domain. Domain names allow A-Za-z0-9 dot and a hyphen (as characters goes).

**Comment by escopecz** [comment]
@biozshock this is how to reproduce:
```
# .env.local
APP_ENV=dev
APP_DEBUG=1
```

`APP_ENV` is the important env.

Can we just use different delimiters than those located in `if (str_contains($value, '*') || str_contains($value, '/') || str_contains($value, '\\') || str_contains($value, '?') || str_contains($value, '^') || str_contains($value, '$')) {`? 

I was just following your steps to test. I know that a domain with a slash isn't valid.

**Comment by matbcvo** [comment]
@biozshock, please rebase onto the 7.1 branch.

**Comment by biozshock** [comment]
@matbcvo Done.
@escopecz Please check with the latest commit. Good find, thanks!

**Review by kuzmany — APPROVED** [review]
Everything looks good to me 👍

**Review by escopecz — APPROVED** [review]
Works nicely. Thanks!

Image

**Comment by promptless-for-oss** [comment]
Promptless prepared a documentation update related to this change.

Triggered by [PR #16006](https://github.com/mautic/mautic/pull/16006)

Documents the Trusted Hosts configuration field validation behavior, clarifying that it accepts both plain domain names and regex patterns for advanced matching.

Review: [Document Trusted Hosts validation and input formats](https://app.gopromptless.ai/suggestions/7ee0c9f3-8eb5-4082-9b7e-043203f2cad2)

**Comment by adiati98** [comment]
Hi @biozshock,

Promptless has suggestions to update the user docs based on this PR. Can you please help us review the content in the [docs PR](https://github.com/mautic/user-documentation/pull/699) and confirm if it's correctly addressing the changes here?

TIA! ✨
