### PR TITLE
DPMMA-3048 Fix campaign execution stuck due to incorrect lead detachment in membership change action

### LINKED ISSUE #14034: Campaign-tasks don't start (& campaign stuck in loop) in 5.1.0
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

**MAIN PROBLEM:**
After adding contacts to the campaigns, the flow/tasks don't start (despite the campaign being active for that contact in his profile). It does not matter how the contact is added to the campaign (via another campaign or directly in his profile-settings).

**EXPLANATION:**
I have 2 campaigns:

**1. Camp. "*REAKT6-01*":** When I add contacts to this campaign [via adding them to the segment "*REAKT-01*"], following things should happen:
Screenshot 2024-07-31 at 12 36 32

So:
-- Getting the tag "*Started campaign: REAKT6-01*" (this works)
-- Sending email #135 (also works)
-- 2 days later adding contact to campaign "*MASTER*":
Screenshot 2024-07-31 at 12 36 43
This does NOT work, instead he gets added every 15 minutes to that MASTER-campaign (based on the contact's History), but that MASTER-campaign does still not start
Screenshot 2024-07-31 at 12 37 50
-- Stopping this "*REAKT6-01*" campaign (this does NOT work, it's not reached, as the flow stucks at the previous step

**2. Camp. "*MASTER*":** This has as starter the empty segment "*NOBODY*", as I want to start it just via other campaigns (like campaign "*REAKT6-01*").

The contact's "Upcoming Events" shows following (the date "July 30, 2024 8:18 pm CEST" is of course already over, but for many contacts **it still tries to add it to the MASTER-campaign every 15 minutes**, already 25+ times):
Screenshot 2024-07-31 at 12 51 21

And checking the contact's Campaigns, that MASTER campaign IS active:
Screenshot 2024-07-31 at 12 55 43

So it looks like that the MASTER-campaign just got "kinda" started, not fully - so it got activated for the contact, but the flow doesn't start. Not just this campaign, some for others.

### How can we reproduce this issue?

I don't know, as I cloned that MASTER-campaign as test and when I added a test-contact to it, that clone-campaign fired correctly. However just cloning and replacing the original with this clone can't really be a solution, as (as I just realized) other campaigns have also this issue (that despite being added to them, their flow doesn't start)

### Relevant log output

```shell
Log is empty
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #14034

## Description
The campaign execution was getting stuck due to an issue with lead detachment in the change membership action. The previous implementation was detaching all contacts, including those newly added to the campaign, which caused problems while trying to save the campaign log after detach.

This PR also addresses an issue in the `testCampaignActionChangeMembership` test. Previously, the test was incorrectly set up: it was adding the contact to both campaigns before executing the campaign action. 

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create two empty segments in Mautic.

3. Create Campaign 1:
   - Start with Segment 1
   - Add an action (e.g., add tag to contact)

4. Create Campaign 2:
   - Start with Segment 2
   - Add "Change Campaigns" action
   - Select "Add to Campaign 1" in the action settings

5. Add a contact to Segment 2 and run the campaigns:
   ```
   php bin/console m:ca:u
   php bin/console m:ca:t
   ```

6. Verify that the campaign execution was successful.

7. Check if the created contact is now a member of Campaign 1.

### CODE REVIEW

File: app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php [hunk 1]
```diff
@@ -128,11 +128,12 @@ protected function createLead(string $leadName): Lead
         return $lead;
     }
 
-    protected function createCampaign(string $campaignName): Campaign
+    protected function createCampaign(string $campaignName, bool $allowRestart = false): Campaign
```
Comment (escopecz) [inline app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php]: Looking at this class name, it's missing the `*Test` suffix. So I bet it doesn't run on `composer test`. Can you please rename the class and file so it would run in CI?

Comment (patrykgruszka) [reply app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php]: This class doesn't contain any tests, it's just an abstract, but without the `abstract` keyword. Should we add the suffix anyway?

Comment (escopecz) [reply app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php]: Oh, then it's fine. It should have been an abstract, but no need to change in this PR. It's unrelated.

**Review by escopecz — APPROVED** [review]
This happened by accident when the EM->clear() method was removed and the code needed to be refactored in https://github.com/mautic/mautic/commit/777e2dc14741d92718c4f53e8130004644838024#diff-88261e62c0ae339645adadf9bb77a8efda5a985a11c5c517c7dcf10da734507a

@biozshock can you please review this too?

**Review by kuzmany — APPROVED** [review]

File: app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php [hunk 2]
```diff
@@ -535,8 +535,36 @@ public function testCampaignActionChangeMembership(): void
...
+        Assert::assertTrue($campaignLeads[0]->getManuallyRemoved());
+        Assert::assertSame($campaign2->getId(), $campaignLeads[1]->getCampaign()->getId());
+        Assert::assertFalse($campaignLeads[1]->getManuallyRemoved());
+    }
+
+    public function testCampaignActionChangeMembershipRestartRotation(): void
+    {
+        $campaign1 = $this->createCampaign('Campaign 1');
+        // create campaign with restart allowed
+        $campaign2 = $this->createCampaign('Campaign 2', true);
```
Comment (biozshock) [inline app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php]: You can change the campaign in place, allowing later to grasp what's going on without a need to review method signature.

```suggestion
        $campaign2 = $this->createCampaign('Campaign 2');
        $campaign2->setAllowRestart(true);
```

File: app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php [hunk 3]
```diff
@@ -128,11 +128,12 @@ protected function createLead(string $leadName): Lead
...
     {
         $campaign = new Campaign();
         $campaign->setName($campaignName);
         $campaign->setIsPublished(true);
+        $campaign->setAllowRestart($allowRestart);
```
Comment (biozshock) [inline app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php]: I'm not a big fan of adding more and more parameters to the methods. This ups the cognitive load. Because the campaign is an object you can freely change it whenever needed later in the test.

```suggestion
    protected function createCampaign(string $campaignName): Campaign
    {
        $campaign = new Campaign();
        $campaign->setName($campaignName);
        $campaign->setIsPublished(true);
```

**Review by biozshock — CHANGES_REQUESTED** [review]

**Review by mikiba — APPROVED** [review]
I tested it in a real application. Before this change I got huge amount of "app.ERROR: CAMPAIGN: Multiple non-persisted new entities were found through the given association graph:" errors and basically every campaign email sending stopped. With this small, but important change everything works as excepted.

File: app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php (hunk 3 above)
Comment (patrykgruszka) [reply app/bundles/CampaignBundle/Tests/Command/AbstractCampaignCommand.php]: Sure, I've changed this.

**Comment by patrykgruszka** [comment]
I've added the suggested changes in tests. It's ready to go.

**Review by escopecz — APPROVED** [review]
Thank you! 👍
