### PR TITLE
Hubspot - Fix errors when the API returns a 401 code

### LINKED ISSUE #11064: Error 500 on Hubspot Plugin Popup config screen
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

Since I upgraded to Mautic 4.2.x it is impossible for me to access the Hubspot plugin.

I have 500 error is returned only on Hubspot Plugin Popup config screen.
I can't disable the plugin on admin screen.

I see the same error message on this old issue : 
https://github.com/mautic/mautic/issues/1391#issuecomment-176197828

I tried to disable the Hubspot plugin. Except that there is no easy way to do this without creating other bugs by side effect.
**Do you have any idea what I can change to fix this bug?**

### How can we reproduce this issue?

Step 1: activate Hubspot plugin
Step 2: update on Mautic 4.2.1
Step 3: try to edit the plugin configuration 

### Relevant log output

```shell
[2022-04-08 18:05:47] mautic.NOTICE: PHP Notice - Undefined index: name - in file /var/www/vhosts/***/httpdocs/plugins/MauticCrmBundle/Integration/HubspotIntegration.php - at line 223 {"settings":{"silence_exceptions":false,"feature_settings":{"objects":{"contacts":"contacts"},"update_mautic":{"email":1,"hs_calculated_mobile_number":1,"city":"1","jobtitle":"1","phone":"1","hs_twitterid":"1","website":"1"},"leadFields":{"email":"email","hs_calculated_mobile_number":"mobile","city":"city","jobtitle":"position","phone":"phone","hs_twitterid":"twitter","website":"website"}},"ignore_field_cache":true,"cache_suffix":".contacts"},"fields":[],"hubsFields":[],"silenceExceptions":false,"hubspotObjects":{"contacts":"contacts"},"object":"contacts","cacheSuffix":".contacts","leadFields":{"error":{"message":"Client error: `GET https://api.hubapi.com/contacts/v2/properties/?hapikey=***&hapikey=***` resulted in a `401 Unauthorized` response:\n{\"status\":\"error\",\"message\":\"The API key used to make this call is expired. View or manage your API key here: https://ap (truncated...)\n","code":401}},"fieldInfo":{"message":"Client error: `GET https://api.hubapi.com/contacts/v2/properties/?hapikey=***&hapikey=***` resulted in a `401 Unauthorized` response:\n{\"status\":\"error\",\"message\":\"The API key used to make this call is expired. View or manage your API key here: https://ap (truncated...)\n","code":401}} []

[2022-04-08 18:05:47] mautic.NOTICE: PHP Notice - Undefined index: label - in file /var/www/vhosts/***/httpdocs/plugins/MauticCrmBundle/Integration/HubspotIntegration.php - at line 225 {"settings":{"silence_exceptions":false,"feature_settings":{"objects":{"contacts":"contacts"},"update_mautic":{"email":1,"hs_calculated_mobile_number":1,"city":"1","jobtitle":"1","phone":"1","hs_twitterid":"1","website":"1"},"leadFields":{"email":"email","hs_calculated_mobile_number":"mobile","city":"city","jobtitle":"position","phone":"phone","hs_twitterid":"twitter","website":"website"}},"ignore_field_cache":true,"cache_suffix":".contacts"},"fields":[],"hubsFields":[],"silenceExceptions":false,"hubspotObjects":{"contacts":"contacts"},"object":"contacts","cacheSuffix":".contacts","leadFields":{"error":{"message":"Client error: `GET https://api.hubapi.com/contacts/v2/properties/?hapikey=***&hapikey=***` resulted in a `401 Unauthorized` response:\n{\"status\":\"error\",\"message\":\"The API key used to make this call is expired. View or manage your API key here: https://ap (truncated...)\n","code":401}},"fieldInfo":{"message":"Client error: `GET https://api.hubapi.com/contacts/v2/properties/?hapikey=***&hapikey=***` resulted in a `401 Unauthorized` response:\n{\"status\":\"error\",\"message\":\"The API key used to make this call is expired. View or manage your API key here: https://ap (truncated...)\n","code":401}} []

[2022-04-08 18:05:47] mautic.NOTICE: PHP Notice - Undefined index: name - in file /var/www/vhosts/***/httpdocs/plugins/MauticCrmBundle/Integration/HubspotIntegration.php - at line 226 {"settings":{"silence_exceptions":false,"feature_settings":{"objects":{"contacts":"contacts"},"update_mautic":{"email":1,"hs_calculated_mobile_number":1,"city":"1","jobtitle":"1","phone":"1","hs_twitterid":"1","website":"1"},"leadFields":{"email":"email","hs_calculated_mobile_number":"mobile","city":"city","jobtitle":"position","phone":"phone","hs_twitterid":"twitter","website":"website"}},"ignore_field_cache":true,"cache_suffix":".contacts"},"fields":[],"hubsFields":[],"silenceExceptions":false,"hubspotObjects":{"contacts":"contacts"},"object":"contacts","cacheSuffix":".contacts","leadFields":{"error":{"message":"Client error: `GET https://api.hubapi.com/contacts/v2/properties/?hapikey=***&hapikey=***` resulted in a `401 Unauthorized` response:\n{\"status\":\"error\",\"message\":\"The API key used to make this call is expired. View or manage your API key here: https://ap (truncated...)\n","code":401}},"fieldInfo":{"message":"Client error: `GET https://api.hubapi.com/contacts/v2/properties/?hapikey=***&hapikey=***` resulted in a `401 Unauthorized` response:\n{\"status\":\"error\",\"message\":\"The API key used to make this call is expired. View or manage your API key here: https://ap (truncated...)\n","code":401}} []

[2022-04-08 18:05:47] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "A form with an empty name cannot have a parent form." at /var/www/vhosts/***/httpdocs/vendor/symfony/form/Form.php line 273 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): A form with an empty name cannot have a parent form. at /var/www/vhosts/***/httpdocs/vendor/symfony/form/Form.php:273)"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108497384-error-500-on-hubspot-plugin-popup-config-screen?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Cr7t3K**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     | Fixes #11064

#### Description:

This PR fixes the infinite loading bug of the Hubspot plugin when it return a 401 error or other unmanaged code.
Hubspot-error-loading.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Setup Hubspot plugin with a valid api key
3. Disable your hubspot api key
4. Return to the plugin, an error message indicates the error encountered with the api

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11416"></a>

PR funded by @PierreAmmeloot from [WebAnyOne](https://www.webanyone.net/)

### CODE REVIEW

**Review by PierreAmmeloot — DISMISSED** [review]

File: plugins/MauticCrmBundle/Api/HubspotApi.php [hunk 1]
```diff
@@ -29,6 +29,17 @@ protected function request($operation, $parameters = [], $method = 'GET', $objec
...
         }
 
+        if (isset($request['error']) && 401 == $request['error']['code']) {
+            $message = $request['error']['message'];
+
+            if (isset($message)) {
+                $cleanMessage = substr(stristr($message, '"message":"'), strlen('"message":"')) ?? $message;
+                throw new ApiErrorException($cleanMessage);
+            } else {
+                throw new ApiErrorException($message);
```
Comment (escopecz) [inline plugins/MauticCrmBundle/Api/HubspotApi.php]: Why would you throw an exception with `$message = null`?

**Review by escopecz — CHANGES_REQUESTED** [review]
Thanks for the fix! Please write PHPUNIT tests for this new code. It is requirement for the PR to be merged.

**Comment by escopecz** [comment]
Also please rebase on 4.4 branch which is for bug fixes and check the failing CI checks. Let me know if you need help with anything.

**Review by escopecz — APPROVED** [review]
I see no issue with the code. Thank you! 👍

**Review by PierreAmmeloot — APPROVED** [review]
