### PR TITLE
Fix PHP Notice - Undefined index: ct

### LINKED ISSUE #7841: Missing clickthrough in the URL query (PublicController.php line 452)
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
PHP Notice about the Undefined index in ../app/bundles/PageBundle/Controller/PublicController.php on line 452

| Q   | A
| --- | ---
| Mautic version | v.2.15.2
| PHP version | 7.2.21 (for Mautic PHP-FPM handler)
| Browser | n./a.

### Steps to reproduce
1. ??
2. - did not find yet
 
### Log errors
Undefined index: ct in /home/path-to/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 452

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

Here is the code from line 451 (starting with //) 
```
        // Unset the clickthrough from the URL query
        $ct = $query['ct'];
        unset($query['ct']);

        // Tak on anything left to the URL
        if (count($query)) {
            $url .= (strpos($url, '?') !== false) ? '&' : '?';
            $url .= http_build_query($query);
        }

        // If the IP address is not trackable, it means it came form a configured "do not track" IP or a "do not track" user agent
        // This prevents simulated clicks from 3rd party services such as URL shorteners from simulating clicks
        $ipAddress = $this->container->get('mautic.helper.ip_lookup')->getIpAddress();
        if ($ipAddress->isTrackable()) {
            // Search replace lead fields in the URL
            /** @var \Mautic\LeadBundle\Model\LeadModel $leadModel */
            $leadModel = $this->getModel('lead');
            $lead      = $leadModel->getContactFromRequest(['ct' => $ct]);

            /** @var \Mautic\PageBundle\Model\PageModel $pageModel */
            $pageModel = $this->getModel('page');
            $pageModel->hitPage($redirect, $this->request, 200, $lead);

            /** @var PrimaryCompanyHelper $primaryCompanyHelper */
            $primaryCompanyHelper = $this->get('mautic.lead.helper.primary_company');
            $leadArray            = ($lead) ? $primaryCompanyHelper->getProfileFieldsWithPrimaryCompany($lead) : [];

            $url = TokenHelper::findLeadTokens($url, $leadArray, true);
        }
```
The issue is easy to correct:
Change line 452:
```
-        $ct = $query['ct'];
+        $ct = $query['ct'] ?? '';
```

Change line 464:
```
-        if ($ipAddress->isTrackable()) {
+        if ($ct && $ipAddress->isTrackable()) {
```

If $query['ct'] data is missing, there is no need to any data process started in line 464.

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR fixed a lot of warnings in Mautic.

`[2021-09-10 07:13:28] mautic.NOTICE: PHP Notice - Undefined index: ct - in file /path/app/bundles/PageBundle/Controller/PublicController.php - at line 450 {"redirectId":"25cac6cf84a40ed70cf5a4741","logger":"[object] (Symfony\\Bridge\\Monolog\\Logger: {})","redirectModel":"[object] (Mautic\\PageBundle\\Model\\RedirectModel: {})","redirect":"[object] (Mautic\\PageBundle\\Entity\\Redirect: Mautic\\PageBundle\\Entity\\Redirect with ID #2212)","url":"https://url/","query":[]} []`

Email trackable links are usually in format:

`https://urlofmautic.com/r/110a69363fd96ed4e28d8e662?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7coxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjI1MTg7fXM6NToiZW1haWwiO2k6MTc5O3M6NDoic3RhdCI7czoyMjojBjMDY5MjI1OTk1NjMzMTkMDc1OCI7czo0OiJsZWFkIjtzOjY6IjI2MzI1NCI7czo3OiJjaGFubmVsIjthOjE6e3M6NToiZW1haWwiO2k6MTc5O319`

But bots (https://github.com/mautic/mautic/issues/9798) transform it to 

`https://urlofmautic.com/r/110a69363fd96ed4e28d8e662?somethingelse=cccccc`

Then looks like for redirect links required always ct param to be track clicks to contact. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create email with link
3. Send email
4. Copy link from email
5. Remove ct param from url and add another one (for exmaple `https://urlofmautic.com/r/110a69363fd96ed4e28d8e662?somethingelse=cccccc`)
6. Before PR it return warning in logs. Now should works properly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10418"></a>

### CODE REVIEW

**Review by dongilbert — CHANGES_REQUESTED** [review]
With this PR as is, we'll get a new warning if the redirect destination is a mautic_asset_download = `$ct is not defined`. 

https://github.com/mautic/mautic/blob/bcf1bcd4449dd66482ebde4e855df9e01f4142d0/app/bundles/PageBundle/Controller/PublicController.php#L504

Please update this PR to also check `if (isset($ct) && false !== ...` on line 504 of the public controller.

**Review by dongilbert — DISMISSED** [review]

File: app/bundles/PageBundle/Controller/PublicController.php [hunk 1]
```diff
@@ -459,10 +459,6 @@ public function redirectAction($redirectId)
         // Get query string
         $query = $this->request->query->all();
 
-        // Unset the clickthrough from the URL query
-        $ct = $query['ct'];
-        unset($query['ct']);
-
```
Comment (dongilbert) [inline app/bundles/PageBundle/Controller/PublicController.php]: OK so I found an issue we're facing. Tests are failing which is good because it allowed me to catch a regression. 

Previously, we would use these lines to prevent the `ct` from being appended back on the URL on line 468. By removing this block, line 468 _does_ append the `ct` back it on to the URL, causing unit tests to fail.

Instead of moving it in the first place, we should probably just use a null coalescing operator - https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

**Comment by dongilbert** [comment]
@kuzmany Can you confirm my findings & fixes?

**Comment by kuzmany** [comment]
@dongilbert I cannot approve my own PR. But I tested it and everything works 👍

**Review by escopecz — DISMISSED** [review]
Code looks good. Just wrapping the code that use `$ct` with a check that it is set (not null) to avoid PHP warning.

**Comment by escopecz** [comment]
@kuzmany I couldn't merge it to 4.1.1 because it is opened against 4.0 and not against 4.1. I tried to change that but that brought a lot of other commits into this PR. I don't yet understand how come the 4.0 branch contains commits that aren't in 4.1 branch but I think it would be simplest to rebase 4.1 in this case.

**Comment by RCheesley** [comment]
@kuzmany let's rebase this on 4.x then we can merge it to be included in the 4.2 release at the end of February. At the mo we can't merge it in the 4.1.2 as it's on the wrong branch. Changing the base results in a lot of conflicts to be resolved.

Thanks!
