### PR TITLE
Fix Sugar/Suite CRM sync for email addresses with an uppercase char

### LINKED ISSUE #7138: Sugar Mautic Sync only Syncing ONCE (not overwriting data)
## Bug Description
I have integrated the Mautic Sugar CRM Sync with Mautic. The sync is working Perfectly. However, there is one major flaw that no one seems to be talking about on the forums.... 

It will sync only ONCE and will not overwrite data after the first sync. 

A typical scenario --> Mautic gives 5 points and then pushes lead to Sugar --> Telemarketer calls this lead and then marks call status in CRM as Not available..... Not available then syncs from Sugar to Mautic. Ok all systems checked ---- except here is where the big flaw is --> next time the telemarketer calls that lead and updates Call Status to "Declined" --> this will not update from Sugar CRM to Mautic because it already pulled it last time as "Not Available" (It wont overwrite it" (And yes Sugar is the Master update direction)---> it is very important to overwrite data in the sync as data is constantly changing. 

In this example, we are wanting to create Segments in Mautic based on the Call Status in the CRM (which are constantly changing). 

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | PHP Version 7.0.32- 0ubuntu0.16.04.1 
| Browser |  CHROME 
| Sugar Version| Sugar Version 6.5.25 (Build 344) with SuiteCRM Version 7.10.9

### Steps to reproduce
1. Create a dropdown field in Sugar CRM and sync it with Mautic. Use the dropdown and select Not available from the dropdown list. Let the cron Run and update in Mautic
2. After "not available" has synced, go back into Sugar CRM , use the drop down on Call Status and select "declined" from the drop down list. 
3. Run the cron to update contacts. You will notice that in Mautic the Call Status is not updated to declined, it remains at the last sync (which is not available). 

 
### Log errors
With that being said. I do have some log errors in my log, but this I believe has nothing to do with the Sync not working because it is working flawlessly except for this issue. 

[2019-01-16 11:50:07] mautic.WARNING: PHP Warning - require(/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: No such file or directory - in file /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

[2019-01-16 11:50:07] mautic.WARNING: PHP Warning - require(/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: No such file or directory - in file /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

[2019-01-16 11:50:07] mautic.ERROR: PHP Notice: require(): Failed opening required '/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php') - in file /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

[2019-01-16 11:50:07] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php') - in file /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

[2019-01-16 11:50:07] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require(): Failed opening required '/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php')" at /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php line 209 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require(): Failed opening required '/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php') at /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209)"} []

[2019-01-16 01:35:06] mautic.NOTICE: RuntimeException: Unable to write in the "/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod" directory (uncaught exception) at /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/symfony/framework-bundle/Command/CacheClearCommand.php line 67 while running console command `cache:clear` [] []

[2019-01-16 05:35:05] mautic.NOTICE: RuntimeException: Unable to write in the "/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod" directory (uncaught exception) at /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/symfony/framework-bundle/Command/CacheClearCommand.php line 67 while running console command `cache:clear` [] []

[2019-01-16 10:35:05] mautic.NOTICE: RuntimeException: Unable to write in the "/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod" directory (uncaught exception) at /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/symfony/framework-bundle/Command/CacheClearCommand.php line 67 while running console command `cache:clear` [] []

[2019-01-16 12:35:05] mautic.NOTICE: RuntimeException: Unable to write in the "/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod" directory (uncaught exception) at /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/symfony/framework-bundle/Command/CacheClearCommand.php line 67 while running console command `cache:clear` [] []

[2019-01-16 14:35:05] mautic.NOTICE: RuntimeException: Unable to write in the "/var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/app/cache/prod" directory (uncaught exception) at /var/www/vhosts/<YOURURLHERE>/httpdocs/mautic/vendor/symfony/framework-bundle/Command/CacheClearCommand.php line 67 while running console command `cache:clear` [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by tsummerer**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | n/a
| Related developer documentation PR URL | n/a
| Issues addressed (#s or URLs) | #7138 #6140
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Currently the code will not properly keep  Mautic and Sugar/SuiteCRM in sync when a Lead's email address has any uppercase characters. 

Within the `SugarcrmIntegration::pushLeads` function, a `$checkEmailsInSugar` array is created. Its keys are forced to be lowercase:
```php
//line 1297
$checkEmailsInSugar[$object][mb_strtolower($lead['email'])] = $lead;
```
Later, this is compared to a list of CRM records. However, the CRM records are NOT normalized to lowercase. If the system does not find a match, then it marks the IntegrationEntity relationship as deleted

```php
//line 1497
foreach ($sugarLeadRecords as $sugarLeadRecord) {
    if ((isset($sugarLeadRecord) && $sugarLeadRecord)) {
        $email           = $sugarLeadRecord['email1'];
        $key             = mb_strtolower($email);
        $leadOwnerEmails = [];
        foreach ($checkEmailsInSugar as $emailKey => $mauticRecord) {
            if ($email == $emailKey) {     <------
```

The fix was simple, I just changed `$email` to `$key`.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Configure the SugarCRM plugin. Be sure to have at least one field pointing from Mautic to CRM
2. Create a Lead in Mautic - it should have uppercase characters in the email address
3. Run the `mautic:integration:synccontacts -i Sugarcrm` (or `fetchleads` (they are synonymous)) command
    This should create the Lead in CRM. 
5. Now, edit your Mautic->CRM field in Mautic. 
6. Run the command again. 

**Expected**: The field updates in CRM
**Actual** : The field does not update. Additionally, the `integration_entity` record has changed from 'lead' to 'lead-deleted'

#### Steps to test this PR:
1. Repeat steps above after installing PR. 

#### List deprecations along with the new alternative:
1. n/a

#### List backwards compatibility breaks:
1. n/a

### CODE REVIEW

**Comment by npracht** [comment]
Hi @tsummerer is it duplicate of https://github.com/mautic/mautic/pull/6694 ?

**Comment by npracht** [comment]
@kuzmany ?

**Comment by tsummerer** [comment]
@npracht - this is completely different from #6694  - that PR is related to case senstive URL's/module names.

**Comment by tsummerer** [comment]
@kuzmany - that would be, I guess, more clear. But it's completely redundant. The `$emailKey` was already moved to lowercase (see my description and line ~1297). So there's no real reason to do it again. 

Given that we strtolower the `$email` variable four lines above, I think that the original developers used `$email` when they meant to use `$key`

**Comment by kuzmany** [comment]
@tsummere Okay, then it looks good for me.

File: plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php [hunk 1]
```diff
@@ -1449,7 +1449,10 @@ private function fetchDncToMautic(Lead $lead, array $data)
      * @param $leadSugarFields
      * @param string $object
      *
-     * @return mixed
+     * @return array The first element is made up of records that exist in Mautic, but which no longer have a match in CRM.
+     *               We therefore assume that they've been deleted in CRM and will mark them as deleted in the pushLeads function (~line 1320).
+     *               The second element contains Ids of records that were explicitly marked as deleted in CRM. ATM, nothing is done with this data.
+     *
```
Comment (escopecz) [inline plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php]:
```suggestion
```
Please remove this line to make Travis CI happy with code style.

File: plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php [hunk 2]
```diff
@@ -1449,7 +1449,9 @@ private function fetchDncToMautic(Lead $lead, array $data)
      * @param $leadSugarFields
      * @param string $object
      *
-     * @return mixed
+     * @return array The first element is made up of records that exist in Mautic, but which no longer have a match in CRM.
+     *               We therefore assume that they've been deleted in CRM and will mark them as deleted in the pushLeads function (~line 1320).
+     *               The second element contains Ids of records that were explicitly marked as deleted in CRM. ATM, nothing is done with this data.
```
Comment (escopecz) [inline plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php]:
```suggestion
     *               The second element contains Ids of records that were explicitly marked as deleted in CRM. ATM, nothing is done with this data.
```
There are also some spaces at the end of this line.
