### PR TITLE
fix #13570 - incorrect banner when multiple theme deletion

### LINKED ISSUE #13570: Incorrect banner information displayed during multiple theme deletion
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

When we insert custom email or landing pages on the Theme page and select more than two of them to be deleted, a banner appears indicating that one theme has been deleted. However, in reality, all selected themes are deleted.

The banner text should reference all the deleted themes instead of just one.

The delete feature itself functions correctly; it's only the message that needs improvement.

### How can we reproduce this issue?

Step 1: Navigate to Settings > Themes
Step 2: Upload two custom themes on your Mautic instance.
Step 3: In the list of all themes, locate the checkbox beside each theme's name and select it.
image

Step 4: At the top of the list, click on "Delete Selected". 
image

Step 5:A banner will appear. Click on "Delete" to confirm.
Step 6: A confirmation banner will appear, displaying only of the names of the deleted themes.

image

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by johbuch**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? 5-x         | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #13570 

## Description
This PR fix the issue when deleting multiple themes in the same times using Delete Selected button.
Before, only one theme name was displaying as deleted (the last one of the selected).
After, deleted banner display for all theme previously deleted

---
### 📋 Steps to test this PR:

1. Navigate to Settings > Themes
2. Upload two custom themes on your Mautic instance.
3. In the list of all themes, locate the checkbox beside each theme's name and select it.
4. Click on Deleted selected button to delete them all in one time
image

5. Now banners appear for each theme deleted
image

### CODE REVIEW

**Review by patrykgruszka — CHANGES_REQUESTED** [review]
I suggest showing just one alert that tells you how many items were deleted, like how it's done for campaigns or emails.

image
image

**Comment by johbuch** [comment]
Hello @andersonjeccel ,

i have changed.

So now if we used the batch delete button for only one theme, then it displays the notice with theme name
image

But if there are more than one theme to be deleted, then it displays the notice with how many have been deleted
image

File: app/bundles/CoreBundle/Controller/ThemeController.php [hunk 1]
```diff
@@ -206,6 +206,17 @@ public function batchDeleteAction(Request $request, ThemeHelperInterface $themeH
             foreach ($themeNames as $themeName) {
                 $flashes = $this->deleteTheme($themeHelper, $themeName);
             }
+
+            if (count($themeNames) > 1) {
```
Comment (shinde-rahul) [inline app/bundles/CoreBundle/Controller/ThemeController.php]: Please move this to the `ThemeController::deleteTheme` method.

**Review by shinde-rahul — CHANGES_REQUESTED** [review]
Please add the PHPUnit test case for coverage.

**Comment by andersonjeccel** [comment]
@johbuch Hi Johan, thanks for tackling this issue!

Would you be up for addressing what Shinde said?

I'll be here to test once you say it's ready

**Comment by johbuch** [comment]
@andersonjeccel ,
of course I just didn't have the time yet but I will ;)

File: app/bundles/CoreBundle/Controller/ThemeController.php (hunk 1 above)
Comment (johbuch) [reply app/bundles/CoreBundle/Controller/ThemeController.php]: hello @shinde-rahul 
no sure how you want me to do it because the deleteTheme method only takes a single theme

**Comment by andersonjeccel** [comment]
@escopecz The failing test here seems to be a temporary issue, do you have permission to run manually again?

**Review by patrykgruszka — DISMISSED** [review]

**Comment by johbuch** [comment]
Hello @andersonjeccel @patrykgruszka 
wait before merging, I am working on a improvement when deleting multiple themes that contain a default theme like Aurora for example, I will still display how many themes have been delete but also that some default theme cannot be removed.
image

I need to update the unit test then I will push a new commit

**Comment by andersonjeccel** [comment]
@johbuch That's really cool, tell me when it's ready!

**Comment by johbuch** [comment]
@andersonjeccel I pushed the changes, let me know if its ok or if I need to make some updates

**Review by Aleks0129 — APPROVED** [review]
Yes it works. 

Screenshot 2024-10-05 at 18 39 03

File: app/bundles/CoreBundle/Controller/ThemeController.php [hunk 2]
```diff
@@ -199,12 +199,36 @@ public function deleteAction(Request $request, ThemeHelperInterface $themeHelper
     public function batchDeleteAction(Request $request, ThemeHelperInterface $themeHelper)
     {
         $flashes = [];
+        $error   = null;
```
Comment (escopecz) [inline app/bundles/CoreBundle/Controller/ThemeController.php]:
```suggestion
        $error   = [];
```
`$error` should be an array as it is expected on line 211.

**Review by escopecz — CHANGES_REQUESTED** [review]
It would be great to also write test that will cover the if/else parts that aren't covered. I' m thinking how to do it if all the themes are core here. How about to copy a core theme folder and rename the folder, give it another name. For example `blank2` and then change the `"install-directory-name": "blank2"` in its composer.json file. Then it will be a new theme that can be deleted.

**Comment by escopecz** [comment]
The failing CI is weird. It is checking a lot of files that were not touched by this PR and some of them do not exist. Try to rebase this PR on the latest 5.x branch if it helps.

File: app/bundles/CoreBundle/Controller/ThemeController.php (hunk 2 above)
Comment (johbuch) [reply app/bundles/CoreBundle/Controller/ThemeController.php]: done

**Comment by johbuch** [comment]
@escopecz you mean write a test that can really test that themes have been deleted ?
Because indeed that's what I saw, we currently don't really test it as they are all core themes

**Comment by escopecz** [comment]
@johbuch yes, I think we should have that covered by a test

**Comment by johbuch** [comment]
@escopecz just to keep you tuned, i have not forgotten to complete this PR, just struggling a bit on the test to install another theme first

**Comment by escopecz** [comment]
@johbuch thanks for the update! I tested it by cloning the blank theme and changing the json value as described in https://github.com/mautic/mautic/pull/14092#pullrequestreview-2350529713 and Mautic then identified it as a new theme. That should work. Or isn't it?

**Comment by johbuch** [comment]
@escopecz I just think that I do it wrongly.
i am trying to it inside my test, so I try to use the themeHelper to copy the theme, install so then I can delete it.
But im probably wrong I guess

**Comment by escopecz** [comment]
@johbuch I tried it and it had a few catches. But it worked out in the end. Please take a look https://github.com/mautic/mautic/pull/14092/commits/99d01fe960f348e99785ad87e4b3bc8accf9fa82. Is it OK with you?

**Comment by johbuch** [comment]
@escopecz it's great thank you
Eventually I would add another non core theme
image
Test to delete both themes as the main issue was about deleting multiple themes in one time
image

Would that be OK if i update with this code ?
Thanks

**Comment by escopecz** [comment]
Great idea! Yes, please make the update.

**Comment by johbuch** [comment]
@escopecz done ;)

**Comment by escopecz** [comment]
@johbuch there is a code style issue reported by GH Actions. Please fix that one. The e2e tests are flaky and failing randomly, so don't worry about those.

**Comment by johbuch** [comment]
Hello @escopecz ,
i don't really understand the issue 
image

**Comment by escopecz** [comment]
Let's see if updating this branch with 5.x fixes it.

**Comment by escopecz** [comment]
I fixed the failing test on the 5.x branch. Re-running.

**Comment by nick-vanpraet** [comment]
> It would be great to also write test that will cover the if/else parts that aren't covered. I' m thinking how to do it if all the themes are core here. How about to copy a core theme folder and rename the folder, give it another name. For example `blank2` and then change the `"install-directory-name": "blank2"` in its composer.json file. Then it will be a new theme that can be deleted.

These changes were made, correct? @escopecz

**Review by escopecz — APPROVED** [review]
Yes, I'd say this is good to go 👍

**Comment by escopecz** [comment]
@shinde-rahul there is one requested change from you. Can you please confirm if you are OK with this or if there is something else to do?

File: app/bundles/CoreBundle/Controller/ThemeController.php (hunk 1 above)
Comment (shinde-rahul) [reply app/bundles/CoreBundle/Controller/ThemeController.php]: @johbuch, I apologize for responding to you late. I re-reviewed the PR, and it's good to go.

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

Thanks @johbuch!!
