### PR TITLE
Upsert functionality

### LINKED ISSUE #288: UpsertInterface and UpsertTrait are missed
### Mautic Version

4.2.x series

### PHP version

8.0.24

### What browsers are you seeing the problem on?

Chrome

### What happened?

A bug happened!

The 500 er is appered when use the current version of the CustomObject with Mautic v4.4.4 or on 5.x branch

### How can we reproduce this issue?

Step 1: Install a new Mautic instance (v4.4.4 or 5.x)
Step 2. Install the CustomBundle
Step 3. Run composer install
Step 4. Try to run migrations
Step 5. The error appears
image

Step 6. Try to open in the browser
Step 7. 500er is here

### Relevant log output

```shell
PHP Fatal error:  Uncaught Error: Interface 'Mautic\CoreBundle\Entity\UpsertInterface' not found in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php:45
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('MauticPlugin\\Cu...')
#3 [internal function]: spl_autoload_call('MauticPlugin\\Cu...')
#4 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/Metadata/EntityMetadata.php(55): ReflectionClass->__construct('\\MauticPlugin\\C...')
#5 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(164): Mautic\CoreBundle\DependencyInjection\Builder\Metadata\EntityMetadata->build()
#6 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(158): Mautic\CoreBundle\DependencyInjection\Builder\BundleMetadataBuilder->buildMappings(Object(Mautic\CoreBun in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php on line 45

Fatal error: Uncaught Error: Interface 'Mautic\CoreBundle\Entity\UpsertInterface' not found in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php:45
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(571): include()
#1 /var/www/html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/v...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('MauticPlugin\\Cu...')
#3 [internal function]: spl_autoload_call('MauticPlugin\\Cu...')
#4 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/Metadata/EntityMetadata.php(55): ReflectionClass->__construct('\\MauticPlugin\\C...')
#5 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(164): Mautic\CoreBundle\DependencyInjection\Builder\Metadata\EntityMetadata->build()
#6 /var/www/html/app/bundles/CoreBundle/DependencyInjection/Builder/BundleMetadataBuilder.php(158): Mautic\CoreBundle\DependencyInjection\Builder\BundleMetadataBuilder->buildMappings(Object(Mautic\CoreBun in /var/www/html/plugins/CustomObjectsBundle/Entity/CustomItem.php on line 45
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aarohiprasad**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [No ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ No] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/acquia/mc-cs-plugin-custom-objects/issues/288

#### Description:

This PR adds the ability to 'upsert' an entity using 'INSERT INTO ... VALUES ... ON DUPLICATE KEY UPDATE' query. It also adds methods to check if the entity has been updated or inserted. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. See https://github.com/acquia/mc-cs-plugin-custom-objects/issues/288

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11654"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
👍 The code looks great

It is not used in the core code yet, but it is needed to fix https://github.com/acquia/mc-cs-plugin-custom-objects/issues/288

**Review by kuzmany — DISMISSED** [review]
👍

**Comment by escopecz** [comment]
@aarohiprasad please fix the failing test so this could be merged.

**Comment by volha-pivavarchyk** [comment]
Works well now for me too. Thanks!

File: app/bundles/LeadBundle/Tests/Entity/ImportTest.php [hunk 1]
```diff
@@ -192,7 +192,7 @@ public function testGetSpeedWhenRunTimeIsUnderOneSecond()
         $import->setInsertedCount(3);
         $import->end(false);
 
-        $this->assertSame(3, $import->getSpeed());
+        $this->assertSame(3.0, $import->getSpeed());
```
Comment (escopecz) [inline app/bundles/LeadBundle/Tests/Entity/ImportTest.php]: Maybe this would do it?
```suggestion
        $this->assertSame(3, (int) $import->getSpeed());
```

Comment (aarohiprasad) [reply app/bundles/LeadBundle/Tests/Entity/ImportTest.php]: Somehow this seems to be working just fine on my local environment exactly the way it was before. I have reset the head and force pushed it. And I am pretty sure that the tests are passing now xD.

**Review by escopecz — APPROVED** [review]
Thanks Aarohi! 👍

**Comment by escopecz** [comment]
@aarohiprasad could you please cherry-pick these changes also for the 4.4 branch and create a duplicate ticket? It looks like the community would like to use the Custom Objects plugin for M4 as well.

**Comment by aarohiprasad** [comment]
Hi @escopecz, please check this PR out.

https://github.com/mautic/mautic/pull/11746

**Comment by escopecz** [comment]
That was fast! Thank you Aarohi!
