### PR TITLE
Fix #15610: Ensure sent counts are correctly tracked for translated emails

### LINKED ISSUE #15610: In the email list view are only the amount of parents sents displayed when there are translated emails
### Mautic Series

6.0.x series

### Mautic installed version

6.0.6

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When sending out emails that have a translation, the total of the emails is not showing the actual amount of emails that were sent out.

The E-Mails goes to 51 contacts (about half German and half English). The list view shows that it was sent to only 26:
Image

Correct would be:
Image

When I open the Parent email it shows the correct number in the chart:
Image

The code suppresses an error (in my system it is not logged):
`PHP Warning - Undefined array key 100`

The problem is on line 1487. 
https://github.com/mautic/mautic/blob/d0a85dfc10798248685ae7e56161610ad9c7695c/app/bundles/EmailBundle/Model/EmailModel.php#L1487

The $emailSettings only contains the email ids for the parents, not the translations. 

### How can we reproduce this issue?

Step 1: Create an email with a translation 
Step 2: Send it.
Step 3: Look at the stats in the list view.

Or run this test: testEmailTranslationBasedOnLocale from the attached file
[EmailModelFunctionalTest.php](https://github.com/user-attachments/files/23340399/EmailModelFunctionalTest.php)

### Relevant log output

```shell
ErrorException {#10112
  #message: "PHP Warning - Undefined array key 100"
  #code: 0
  #file: "
/var/www/html/app
/
bundles/EmailBundle/Model/EmailModel.php
"
  #line: 1520
  #severity: E_WARNING
  trace: {
    
/var/www/html/app
/
bundles/EmailBundle/Model/EmailModel.php:1520
 {
      
EmailModel->sendEmail(Email $email, $leads, $options = [])
 …
      › // $this->getRepository()->upCountSent($emailId, (int) $count, (bool) $emailSettings[$emailId]['isVariant']);
      › $this->getRepository()->upCountSent($emailId, (int) $count, (bool) $emailSettings[$emailId]['isVariant']);
      › 
    }
    
/var/www/html/app
/
bundles/EmailBundle/Model/EmailModel.php:1093
 {
      
EmailModel->sendEmailToLists(Email $email, $lists = null, $limit = null, $batch = null, ?OutputInterface $output = null, $minContactId = null, $maxContactId = null, ?int $maxThreads = null, ?int $threadId = null): array
 …
      › 
      › $listErrors = $this->sendEmail($email, $leads, $options);
      › 
    }
    
bundles/EmailBundle/Controller/AjaxController.php:64
 {
      
AjaxController->sendBatchAction(Request $request): JsonResponse
 …
      › $session->set('mautic.email.send.active', true);
      › [$batchSentCount, $batchFailedCount, $batchFailedRecipients] = $model->sendEmailToLists($entity, null, $limit);
      › 
    }
    
/var/www/html/vendor
/symfony/http-kernel/
HttpKernel.php:181
 {
      
HttpKernel->handleRaw(Request $request, int $type = self::MAIN_REQUEST): Response
 …
      › // call controller
      › $response = $controller(...$arguments);
      › 
    }
    
/var/www/html/vendor
/symfony/http-kernel/
HttpKernel.php:76
 {
      
HttpKernel->handle(Request $request, int $type = HttpKernelInterface::MAIN_REQUEST, bool $catch = true): Response
 …
      › try {
      ›     return $response = $this->handleRaw($request, $type);
      › } catch (\Throwable $e) {
    }
    
bundles/CoreBundle/Controller/CommonController.php:111
 {
      
CommonController->forwardWithPost($controller, array $request = [], array $path = [], array $query = [])
 …
      › 
      ›     return $this->container->get('http_kernel')->handle($subRequest, HttpKernelInterface::SUB_REQUEST);
      › }
    }
    
bundles/CoreBundle/Controller/AjaxController.php:128
 {
      
AjaxController->executeAjaxAction(Request $request, $action, $bundle = null)
 …
      › if (method_exists($this, $action.'Action')) {
      ›     return $this->forwardWithPost(
      ›         static::class.'::'.$action.'Action',
    }
    
/var/www/html/vendor
/symfony/http-kernel/
HttpKernel.php:181
 {
      
HttpKernel->handleRaw(Request $request, int $type = self::MAIN_REQUEST): Response
 …
      › // call controller
      › $response = $controller(...$arguments);
      › 
    }
    
/var/www/html/vendor
/symfony/http-kernel/
HttpKernel.php:76
 {
      
HttpKernel->handle(Request $request, int $type = HttpKernelInterface::MAIN_REQUEST, bool $catch = true): Response
 …
      › try {
      ›     return $response = $this->handleRaw($request, $type);
      › } catch (\Throwable $e) {
    }
    
bundles/CoreBundle/Controller/CommonController.php:111
 {
      
CommonController->forwardWithPost($controller, array $request = [], array $path = [], array $query = [])
 …
      › 
      ›     return $this->container->get('http_kernel')->handle($subRequest, HttpKernelInterface::SUB_REQUEST);
      › }
    }
    
bundles/CoreBundle/Controller/AjaxController.php:100
 {
      
AjaxController->delegateAjaxAction(Request $request, AuthorizationCheckerInterface $authorizationChecker)
 …
      › if ($classExists) {
      ›     return $this->forwardWithPost(
      ›         $namespace.'\\'.$bundle.'Bundle\\Controller\\AjaxController::executeAjaxAction',
    }
    
/var/www/html/vendor
/symfony/http-kernel/
HttpKernel.php:181
 {
      
HttpKernel->handleRaw(Request $request, int $type = self::MAIN_REQUEST): Response
 …
      › // call controller
      › $response = $controller(...$arguments);
      › 
    }
    
/var/www/html/vendor
/symfony/http-kernel/
HttpKernel.php:76
 {
      
HttpKernel->handle(Request $request, int $type = HttpKernelInterface::MAIN_REQUEST, bool $catch = true): Response
 …
      › try {
      ›     return $response = $this->handleRaw($request, $type);
      › } catch (\Throwable $e) {
    }
    
/var/www/html/vendor
/symfony/http-kernel/
Kernel.php:197
 {
      
Kernel->handle(Request $request, int $type = HttpKernelInterface::MAIN_REQUEST, bool $catch = true): Response
 …
      › try {
      ›     return $this->getHttpKernel()->handle($request, $type, $catch);
      › } finally {
    }
    
/var/www/html/app
/
AppKernel.php:102
 {
      AppKernel->handle(Request $request, $type = HttpKernelInterface::MAIN_REQUEST, $catch = true): Response …
      › 
      ›     return parent::handle($request, $type, $catch);
      › }
    }
    
/var/www/html/app
/
middlewares/CORSMiddleware.php:78
 {
      
CORSMiddleware->handle(Request $request, $type = self::MAIN_REQUEST, $catch = true): Response
 …
      › 
      › $response = $this->app->handle($request, $type, $catch);
      › 
    }
    
/var/www/html/app
/
middlewares/HSTSMiddleware.php:39
 {
      
HSTSMiddleware->handle(Request $request, $type = self::MAIN_REQUEST, $catch = true): Response
 …
      › {
      ›     $response = $this->app->handle($request, $type, $catch);
      › 
    }
    
/var/www/html/app
/
middlewares/CatchExceptionMiddleware.php:28
 {
      
CatchExceptionMiddleware->handle(Request $request, $type = self::MAIN_REQUEST, $catch = true): Response
 …
      › try {
      ›     $response = $this->app->handle($request, $type, $catch);
      › 
    }
    
/var/www/html/app
/
middlewares/Dev/IpRestrictMiddleware.php:52
 {
      
IpRestrictMiddleware->handle(Request $request, $type = self::MAIN_REQUEST, $catch = true): Response
 …
      › if (in_array($request->getClientIp(), $this->allowedIps) || false !== getenv('DDEV_TLD')) {
      ›     return $this->app->handle($request, $type, $catch);
      › }
    }
    
/var/www/html/app
/
middlewares/VersionCheckMiddleware.php:58
 {
      
VersionCheckMiddleware->handle(Request $request, $type = self::MAIN_REQUEST, $catch = true): Response
 …
      › 
      ›     return $this->app->handle($request, $type, $catch);
      › }
    }
    
/var/www/html/app
/
middlewares/TrustMiddleware.php:42
 {
      
TrustMiddleware->handle(Request $request, $type = self::MAIN_REQUEST, $catch = true): Response
 …
      › 
      ›     return $this->app->handle($request, $type, $catch);
      › }
    }
    
/var/www/html/app
/
middlewares/StackedHttpKernel.php:55
 {
      
StackedHttpKernel->handle(Request $request, $type = HttpKernelInterface::MAIN_REQUEST, $catch = true): Response
 …
      ›     return $this->kernel
      ›         ->handle($request, $type, $catch);
      › }
    }
    
/var/www/html
/
index.php:26
 {
      › $request  = Request::createFromGlobals();
      › $response = $kernel->handle($request);
      › $response->send();
    }
  }
}
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️ 
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ✔️ 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #15610  

## Description

This fixes a bug where the "sent" count for emails with translations was not being correctly aggregated to the parent email.

This change introduces a new helper method to correctly identify if an email ID belongs to a parent or a translation and ensures that the sent count is always attributed to the correct parent email entity.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new email and add one or more translations for it.
3. Create a segment with contacts that have the `preferred_locale` field set to the languages of your translated emails.
4. Create a campaign that sends the email created in step 1 to the segment from step 2.
5. Trigger the campaign and let it execute.
6. Check the "Sent" count for the parent email. It should now correctly show the total number of emails sent across the parent and all its translations

### CODE REVIEW

File: app/bundles/EmailBundle/Model/EmailModel.php [hunk 1]
```diff
@@ -2321,4 +2323,29 @@ public function buildUrl($route, $routeParams = [], $absolute = true, $clickthro
...
+    private function isEmailVariant(int $emailId, array $emailSettings): bool
+    {
+        // Check if it's a parent email in emailSettings
+        if (isset($emailSettings[$emailId])) {
+            return (bool) $emailSettings[$emailId]['isVariant'];
+        }
+
+        // It's likely a translation - find it in translations and check if the parent is a variant
+        foreach ($emailSettings as $settings) {
+            if (!empty($settings['translations']) && is_array($settings['translations']) && isset($settings['translations'][$emailId])) {
```
Comment (escopecz) [inline app/bundles/EmailBundle/Model/EmailModel.php]: This will do the same, right? If the last condition is true then the first 2 must be true as well.
```suggestion
            if (isset($settings['translations'][$emailId])) {
```

File: app/bundles/EmailBundle/Tests/Model/EmailModelTranslationCountFunctionalTest.php [hunk 2]
```diff
@@ -0,0 +1,211 @@
...
+use Mautic\CampaignBundle\Entity\Campaign;
+use Mautic\CampaignBundle\Entity\Event;
+use Mautic\CampaignBundle\Entity\Lead as CampaignLead;
+use Mautic\CoreBundle\Test\MauticMysqlTestCase;
+use Mautic\EmailBundle\Entity\Email;
+use Mautic\EmailBundle\Model\EmailModel;
+use Mautic\LeadBundle\Entity\Lead;
+use Mautic\LeadBundle\Model\LeadModel;
+
+class EmailModelTranslationCountFunctionalTest extends MauticMysqlTestCase
```
Comment (escopecz) [inline app/bundles/EmailBundle/Tests/Model/EmailModelTranslationCountFunctionalTest.php]: All new classes should be final by default
```suggestion
final class EmailModelTranslationCountFunctionalTest extends MauticMysqlTestCase
```

**Review by escopecz — CHANGES_REQUESTED** [review]
I don't see any major issues with the code. Just 2 small suggestions.

This has never worked correctly, right? Or was it working in M4?

File: app/bundles/EmailBundle/Tests/Model/EmailModelTranslationCountFunctionalTest.php (hunk 2 above)
Comment (shinde-rahul) [reply app/bundles/EmailBundle/Tests/Model/EmailModelTranslationCountFunctionalTest.php]: I always forgot to add the final keyword 😟

**Review by escopecz — DISMISSED** [review]
Thanks Rahul! I don't have any other issues with the code change 👍

**Comment by npracht** [comment]
Hello @adiux, this is the fix for the issue you reported. Can you please have a quick test then we can press merge right now :)

**Comment by adiux** [comment]
@npracht since @rahuld-dev is working for me, I dont think I can do the review?

**Comment by npracht** [comment]
@adiux as far as we have a fully trusted third party (@escopecz) if you do an honnest one more test we can go :)

File: app/bundles/EmailBundle/Model/EmailModel.php (hunk 1 above)
Comment (adiux) [reply app/bundles/EmailBundle/Model/EmailModel.php]: @escopecz I think if you dont check if it is empty (or isset) you will get a warning: 
PHP Warning:  Undefined array key "translations"

<?php
$settings = [];
echo "one:";
var_dump(is_array($settings['translations']));
echo "two:";
var_dump(!empty($settings['translations']) && is_array($settings['translations']));
?>

Comment (adiux) [reply app/bundles/EmailBundle/Model/EmailModel.php]:
```
<?php
$settings = [];
echo "one";
var_dump(is_array($settings['translations']));
echo "two";
var_dump(!empty($settings['translations']) && is_array($settings['translations']));
?>
```

**Review by kuzmany — DISMISSED** [review]
Seems OK to me. Good to go 👍

**Comment by npracht** [comment]
I was about to click merge, but:
> The Long Term Support version for Mautic 6 is 6.0. This is actively supported until 30th September 2025 and receives security support until 30th September 2026.

Should we rebase this on 7.x ? @escopecz

File: app/bundles/EmailBundle/Model/EmailModel.php (hunk 1 above)
Comment (escopecz) [reply app/bundles/EmailBundle/Model/EmailModel.php]: The `isset` doesn't throw warnings if any array key exists or not. Even if the `$settings` variable doesn't exist. See

https://legacy-sandbox.onlinephpfunctions.com?s=s7EvyCjg5eLlUknNTczM8UxRsFUwtgYJZKYpaGQWF6eWaKgAiZLMvPTiaPWSosS84pzEksz8vGL12GiYplhNTYVqXi4FIEhNzshXUEqtyCwuKVYCGlSrkJpTnIoqm5dfkAqWAwA%2C&v=8.2.20

It will return true only if all the array keys in the checked chain exist and the value is not NULL. So that's what we need.

**Comment by escopecz** [comment]
I can see there is one PR merged into 6.0.7: https://github.com/mautic/mautic/pulls?q=is%3Apr+milestone%3A6.0.7+is%3Aclosed

@RCheesley @jos0405 shall we extend the active support for M6? I think we should have active support for at least 1 Mautic version at any point in time. And M7 is at least 1 month away.

**Comment by RCheesley** [comment]
@escopecz that PR was one we made to all branches because GitHub Codespaces was breaking, making it difficult to test PRs. It's not something that is released for the application itself. I would prefer that we rebase this to the 7.0 branch and release with the Release Candidate, as 6.0 is now out of active support for over a month.

**Comment by npracht** [comment]
@shinde-rahul we are very sorry but can you rebase against 7.x branch please ?

**Comment by shinde-rahul** [comment]
@escopecz @kuzmany @npracht I have rebased it with 7.x. Please re-review.

**Review by escopecz — APPROVED** [review]
I have no issues with the code changes 👍

**Review by kuzmany — APPROVED** [review]
Seems good to me.
