### PR TITLE
Fix doNotContact on contacts created through API

### LINKED ISSUE #9224: Add DNC (do not contact) while creating contact through API doesn't work
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When creating a contact through the API, and while at the same time including `doNotContact` information, the `doNotContact` config isn't saved to the lead immediately upon creation. This worked in Mautic 2.16 and is therefore a regression in Mautic 3.0+

| Q   | A
| --- | ---
| Mautic version | 3.0 and later (worked in 2.16)
| PHP version | 7.2
| Browser | N/A (API) 

### Steps to reproduce
1. Make sure you have set up Mautic's API (if you don't have an instance to test with, you can use https://mautibox.com/staging/api with user/pass as Basic Auth: admin/mautic)
2. Do a `POST` request (e.g. with [Postman](https://www.postman.com/)) to `YOUR_MAUTIC_URL/api/contacts/new` with the following JSON content:
```JSON
{
    "firstname": "John",
    "lastname": "APIDoe",
    "address2": "Sam & Sons",
    "email": "test@mautic.api",
    "type": "volunteer",
    "owner": 1,
    "points": 3,
    "tags": [
        "APItag1",
        "APItag2"
    ],
    "doNotContact": [
        {
            "channel": "email",
            "reason": 2
        }
    ]
}
```
3. Notice that there is no `doNotContact` information in the Lead you just created:

image

4. Do the exact same POST request another time, notice there is `doNotContact` information now:

image

This is because setting `doNotContact` currently only works when updating an existing Lead (or creating a new one which then gets merged into another one). This is due to a change that got introduced in Mautic 3.0, where `doNotContact` functionality got moved to the dedicated `DoNotContact` model, while it was part of the `LeadModel` before (e.g. in Mautic 2.16). Therefore, this is a regression.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.1
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/168
| Issue(s) addressed                     | Fixes #9224 

#### Steps to test this PR:
1. Reproduce the bug with the steps described at https://github.com/mautic/mautic/issues/9224
2. Apply this PR locally or via Mautibox: [this PR](https://mautibox.com)
3. Retry with the steps mentioned in #9224, should work as described now

### CODE REVIEW

File: app/bundles/LeadBundle/Model/DoNotContact.php [hunk 1]
```diff
@@ -74,25 +74,20 @@ public function removeDncForContact($contactId, $channel, $persist = true, $reas
...
-     * @param bool         $allowUnsubscribeOverride
+     * @param string|array $channel If an array with an ID, use the structure ['email' => 123]
+     * @param int          $reason  Must be a class constant from the DoNotContact class
      *
      * @return bool|DNC If a DNC entry is added or updated, returns the DoNotContact object. If a DNC is already present
      *                  and has the specified reason, nothing is done and this returns false
      */
     public function addDncForContact(
-        $contactId,
+        int $contactId,
```
Comment (dennisameling) [inline app/bundles/LeadBundle/Model/DoNotContact.php]: This might be a breaking change for anyone who's using this function e.g. in plugins and is not already providing the right data types.

I'm happy to move this snippet to a separate PR for Mautic 4.0; it could've prevented this bug from occurring in the first place, but it's rather a code optimization than part of this bug fix.

Comment (RCheesley) [reply app/bundles/LeadBundle/Model/DoNotContact.php]: If it's a BC break and the rest of the bug can be fixed without it, then we should move this part to a separate PR I believe.

**Comment by dennisameling** [comment]
Hi! To keep things central regarding issues around Do Not Contact (DNC), I created a JIRA issue to track all issues related to DNC in a single place. That way, we can more efficiently fix the several bugs that were reported. Please check it out: https://mautic.atlassian.net/browse/TPROD-72

**Comment by dennisameling** [comment]
@StoppingBuck would you mind testing this one as well, as it's also DNC API-related?

**Review by RCheesley — APPROVED** [review]
Identified the bug as per the issue:

screenshot-nimbus-capture-2020 09 21-13_11_04

screenshot-nimbus-capture-2020 09 21-13_11_55

After applying the PR, the DNC info is set on the first POST:

screenshot-nimbus-capture-2020 09 21-13_15_10

**Review by mabumusa1 — APPROVED** [review]
I tested the code, it works as expected.
