### PR TITLE
Fix Installer Exception Handling - TPROD-194

### LINKED ISSUE #9473: Installation throwing 500 error if credentials are incorrect
## Bug Description
I noticed while installing 3.2.1 today from the build packages that when my database credentials were incorrect during installation, instead of showing a warning it was crashing with a 500 error, and the following was in the error log:

```
[2020-12-05 12:08:47] mautic.WARNING: PHP Warning - Cannot use a scalar value as an array - in file /var/www/m/app/bundles/InstallBundle/Install/InstallService.php - at line 331 {"step":"[object] (Mautic\\InstallBundle\\Configurator\\Step\\DoctrineStep: {\"driver\":\"pdo_mysql\",\"host\":\"localhost\",\"table_prefix\":\"mau_\",\"port\":\"3306\",\"name\":\"redacted\",\"user\":\"redacted\",\"password\":\"redacted\",\"backup_tables\":0,\"backup_prefix\":\"bak_\"})","dbParams":{"driver":"pdo_mysql","host":"localhost","table_prefix":"mau_","port":"3306","name":"redacted","user":"redacted","password":"redacted","backup_tables":0,"backup_prefix":"bak_"},"translator":"[object] (Mautic\\CoreBundle\\Translation\\Translator: {})","messages":true,"schemaHelper":"[object] (Mautic\\InstallBundle\\Helper\\SchemaHelper: {})"} []
[2020-12-05 12:08:47] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'redacted'@'localhost' to database 'redacted'" at /var/www/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'redacted'@'localhost' to database 'redacted' at /var/www/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'redacted'@'localhost' to database 'redacted' at /var/www/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'redacted'@'localhost' to database 'redacted' at /var/www/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)"} []
```

This is a pretty ugly experience for the end-user, as they do not know what went wrong, and instead are greeted by our good friend the MautiBot.

Seems to relate to this line for the warning: https://github.com/mautic/mautic/blob/features/app/bundles/InstallBundle/Install/InstallService.php#L331

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.4.3
| Browser | Chrome

### Steps to reproduce
1. Install Mautic and enter incorrect credentials when setting up the database connection
2. Note that you get a hard error, rather than a warning that the credentials may be invalid.
 
### Log errors

As above ^_-

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL |
| Issue(s) addressed                     | Fixes #9473 

#### Description:
In 4.0alpha, going through the first step of the installer to configure and install the schema fails if using a db table prefix. It works fine without one but one throws an exception like `An error occurred while attempting to add default data: Table db_leads does not exist!`

To reproduce:
1. Go through the UI installer (delete or rename app/config/local.php)
2. Enter the database credentials with a db table prefix and proceed to the next step
3. Note the error
4. Repeat without a prefix and you'll be able to complete the installation
**Update**
@alanhartless wrote some patches that fix the issues on the UI.
 The bug exists on the CLI part of the installer, To reproduce the issue
1. Make sure the cache folder is empty.
2. Make sure `local.php` does not exist.
3. Make sure the database is empty.
3. Run the command to install Mautic `php bin/console mautic:install --db_port 3306 --db_host db --db_name db --db_user db --db_password db --db_table_prefix ma_ https://mautic.ddev.site/ --env=dev`
4. Notice that the prefix is not honored 

Run this script to reproduce the issue and for quick testing 
```
#!/bin/bash         
mysql -udb -pdb -e "drop database db; create database db"
rm -rf /var/www/html/var/cache/*
rm /var/www/html/app/config/local.php
php bin/console mautic:install --db_port 3306 --db_host db --db_name db --db_user db --db_password db --db_table_prefix ma_ https://mautic.ddev.site/ --env=dev --admin_firstname=admin --admin_lastname=admin --admin_username=user --admin_email=email@domainc.com --admin_password=password
```

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Try to install with wrong DB settings, no exception should show
3. Add a prefix, database tables should have a prefix

### CODE REVIEW

File: app/bundles/InstallBundle/Install/InstallService.php [hunk 1]
```diff
@@ -308,19 +308,20 @@ public function createDatabaseStep($step, $dbParams)
     {
         $translator = $this->translator;
 
-        $messages = $this->validateDatabaseParams($dbParams);
+        $status   = $this->validateDatabaseParams($dbParams);
```
Comment (alanhartless) [inline app/bundles/InstallBundle/Install/InstallService.php]: validateDatabaseParams() is returning an array of validation errors as well which would be ignored with this change.

**Review by alanhartless — CHANGES_REQUESTED** [review]
I'm still getting the same error when I try installing using a database table prefix with this PR. 

```
An error occurred while attempting to add default data: Table mautic_leads does not exist!
```

**Comment by alanhartless** [comment]
Hmmm, this is odd. It seems to work when I don't have xdebug on but does not when I have it off. Maybe a timing issue where the slightest delay in processing allows it to work in my Docker environment. Still doing some digging.

**Comment by alanhartless** [comment]
Ok, it's something to do with Symfony's cache and Doctrine's EntityManager (the reason xdebug affected it above is that I have two containers, one with xdebug and one without, so each had their own compiled cache and thus not related directly to the issue). Deleting app/config/local.php and nuking Symfony's cache will replicate the issue and I've been able to track it down to https://github.com/mautic/mautic/blob/0f6bbbb3579f5a33a8264fd271b7e3881cc0b561/app/bundles/InstallBundle/Helper/SchemaHelper.php#L162 does not include the table prefix in the table names for the metadata if going through a clean install. If app/config/local.php exists with the prefix defined, deleting the cache, and going through the installer works.

**Comment by alanhartless** [comment]
Doctrine is caching the table names in /prod/doctrine/orm/default_metadata.php and the file is only created when the cache is warmed up (DoctrineMetadataCacheWarmer) so we can't just delete the one file or lose it's benefits. I'd advocate that we remove support for naming a prefix through the UI installer but Mautic and the `mautic:install` command can continue to support one.

**Comment by mabumusa1** [comment]
@alanhartless How can I support pushing this PR forward?

**Comment by RCheesley** [comment]
@mabumusa1 we had a discussion on this topic in Slack: https://mautic.slack.com/archives/C01KB7GQFCL/p1619382546118000

**Comment by alanhartless** [comment]
@mabumusa1 would you like help implementing as discussed in the slack channel?

**Comment by mabumusa1** [comment]
@alanhartless @RCheesley this PR is ready, please give it a test


Thanks for @ts-navghane for his support on this PR

**Comment by RCheesley** [comment]
Tried to test but I am getting this error:

`[2021-06-24 13:28:37] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Attempted to call an undefined method named "getServerVersion" of class "Mautic\InstallBundle\Helper\SchemaHelper"." at /var/www/html/app/bundles/InstallBundle/Controller/InstallController.php line 112 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Attempted to call an undefined method named \"getServerVersion\" of class \"Mautic\\InstallBundle\\Helper\\SchemaHelper\". at /var/www/html/app/bundles/InstallBundle/Controller/InstallController.php:112)"} []`

I think this relates to a PR that was [recently merged](https://github.com/mautic/mautic/pull/9739) (dynamic database detection) where this was removed (see [these lines](https://github.com/mautic/mautic/pull/9739/files#diff-5ab18406219428fd4574c6d6a7f61684e24d480d388f50614e80ab7bf401e89fL104)).

I have just pulled in the latest changes from Features to see if that helps!

**Comment by RCheesley** [comment]
@mabumusa1 I think that this PR may need to be revisited - when I apply it I am consistently getting the message above as soon as I try to enter the database credentials. 

I think that it may be related to the changes that were made in the PR that I mention - please can you review?  

You may need to ping Dennis but he is unavailable until the end of the month :(

File: app/bundles/InstallBundle/Controller/InstallController.php [hunk 2]
```diff
@@ -99,37 +102,43 @@ public function stepAction($index = 0)
...
-                        } elseif (is_array($messages) && !empty($messages)) {
+                        if (!empty($messages)) {
                             $this->handleInstallerErrors($form, $messages);
+                            break;
                         }
-                        break;
 
+                        // XXX Regression: we used to also get this if database created but configuration not saved
+                        $schemaHelper             = new SchemaHelper($dbParams);
+                        $formData->server_version = $schemaHelper->getServerVersion();
```
Comment (RCheesley) [inline app/bundles/InstallBundle/Controller/InstallController.php]: This was removed in https://github.com/mautic/mautic/pull/9739 so we should not be re-adding it here

File: app/bundles/InstallBundle/Controller/InstallController.php [hunk 3]
```diff
@@ -14,6 +14,7 @@
 use Doctrine\DBAL\DBALException;
 use Mautic\CoreBundle\Configurator\Configurator;
 use Mautic\CoreBundle\Controller\CommonController;
+use Mautic\InstallBundle\Helper\SchemaHelper;
```
Comment (RCheesley) [inline app/bundles/InstallBundle/Controller/InstallController.php]: This was removed in https://github.com/mautic/mautic/pull/9739 so we should not be adding it back in (as far as I know at least!)

**Review by RCheesley — CHANGES_REQUESTED** [review]

File: app/bundles/InstallBundle/Controller/InstallController.php (hunk 2 above)
Comment (mabumusa1) [reply app/bundles/InstallBundle/Controller/InstallController.php]: I removed these lines, I do not think we need them given the PR #9739 I tested locally on both CLI and web and it worked as expected, I removed them

File: app/bundles/InstallBundle/Controller/InstallController.php (hunk 3 above)
Comment (mabumusa1) [reply app/bundles/InstallBundle/Controller/InstallController.php]: This helper is not needed as well

**Comment by RCheesley** [comment]
Still not getting anywhere with this fix - when I try to install I get an error message:

An error occurred while attempting to add default data: Table mau_leads does not exist!

screenshot-mautic4 ddev site-2021 06 28-19_53_30

The tables are all created, without the prefix:

screenshot-mautic4 ddev site_8037-2021 06 28-19_57_23

so something isn't quite right!

We will have to go ahead and make the Release Candidate release with a caveat about not installing with a prefix while we work on this some more!

Thanks for all the work to date!

**Comment by mabumusa1** [comment]
@RCheesley I double-checked, it worked well on both CLI and the web, I think the thing you need to clear the cache before you start the test.

here is an example of installing with a prefix using the web interface

image

For CLI testing, please run the bash script in the body of the PR at the top.

**Comment by RCheesley** [comment]
I cloned down Mautic from the features branch, checked out your PR, and did the install there in the GUI - so there was no cache as I had started from scratch and had manually deleted any tables in the database.

I'll test it again, but I tried it several times!

**Comment by RCheesley** [comment]
Here is a screencast: https://youtu.be/69iIM2TNJkc which shows this behaviour

**Comment by n-azimy** [comment]
@RCheesley I can confirm this behavior. After checking out on this PR, the problem is still present.

Bildschirmfoto 2021-07-13 um 11 13 06

**Comment by RCheesley** [comment]
Thanks so much for testing @n-azimy - Glad it is not only me! 😅 

Are you testing locally with DDEV?

**Comment by n-azimy** [comment]
I did not test with ddev, but locally on a manually set up web server (MAMP)

File: app/bundles/InstallBundle/Install/InstallService.php [hunk 4]
```diff
@@ -286,90 +242,74 @@ public function validateDatabaseParams($dbParams)
...
-     * @param array              $dbParams
-     *
-     * @return array|bool
      */
-    public function createDatabaseStep($step, $dbParams)
+    public function createDatabaseStep(StepInterface $step, array $dbParams): array
     {
-        $translator = $this->translator;
-
         $messages = $this->validateDatabaseParams($dbParams);
```
Comment (luguenth) [inline app/bundles/InstallBundle/Install/InstallService.php:264]:
```suggestion
        // Clear Cache to get the prefixes working
        $this->cacheHelper->nukeCache();

        $messages = $this->validateDatabaseParams($dbParams);
```

Comment (luguenth) [reply app/bundles/InstallBundle/Install/InstallService.php:264]: This Line will clear the cache and will build a new cache with the right prefix

**Review by luguenth — CHANGES_REQUESTED** [review]

**Comment by luguenth** [comment]
Found no other way than clearing the cache to force to rebuild the container. It should work now, but'll take longer because of the new compilation of the controller in the process :/

**Comment by n-azimy** [comment]
Works for me both via the GUI and CLI, despite the longer loading times due to the additional cache clear.  👍

**Review by n-azimy — DISMISSED** [review]
Works for me both via the GUI and CLI, despite the longer loading times due to the additional cache clear. 👍

**Comment by luguenth** [comment]
There are still failing DB tests. It says  `Undefined index: env`. Maybe the Cleared Cache is crashing the testing...

**Comment by dennisameling** [comment]
@luguenth The `find` function of the `Application` wasn't mocked in the test. Fixed in https://github.com/mautic/mautic/pull/9934/commits/ae8ba46a236c0a7eaf5be2a3927e53940f5fb2ae. I see the tests pass locally on my machine now, but haven't tested if the functionality still works as expected. Let's wait for CI to finish the tests and then have someone re-test a UI + CLI installation 👍🏼

**Comment by RCheesley** [comment]
OK so here's my results from testing:

Provided install command was insufficient - had to specify additional variables:

`ddev exec bin/console mautic:install --mailer_from_name="DDEV" --mailer_from_email="mautic@ddev.local" --mailer_transport="smtp" --mailer_host="localhost" --mailer_port="1025" --db_driver="pdo_mysql" --db_host="db" --db_port="3306" --db_name="db" --db_user="db" --db_password="db" --db_table_prefix="mau_" --db_backup_tables="false" --admin_email="admin@mautic.local" --admin_password="mautic" https://mautic.ddev.site --env=dev`

Removed the --db_table_prefix="mau_" to test without a prefix.

**With prefix**
Install via the UI ✅ 
Install via CLI ✅ 

**No prefix**
Install via the UI ✅  
Install via CLI ❌ 

Tried without the db_table_prefix option and providing it but empty (eg --db_table_prefix="") but neither resulted in a positive outcome

```
0 - Checking installation requirements...
Ready to Install!
1 - Creating database...
1.1 - Creating schema...
16:23:46 ERROR     [mautic] SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.lead_fields' doesn't exist
Errors in schema configuration/installation:
  - [error] An error occurred while attempting to install the data: Notice: Undefined index: table_prefix
Install canceled
Failed to execute command bin/console mautic:install --mailer_from_name=DDEV --mailer_from_email=mautic@ddev.local --mailer_transport=smtp --mailer_host=localhost --mailer_port=1025 --db_driver=pdo_mysql --db_host=db --db_port=3306 --db_name=db --db_user=db --db_password=db --db_table_prefix= --db_backup_tables=false --admin_email=admin@mautic.local --admin_password=mautic https://mautic.ddev.site --env=dev: exit status 255

```

I haven't been able to get the CLI to work when I do not provide a prefix - if I am getting the command wrong please do enlighten me!

**Comment by luguenth** [comment]
Hi @RCheesley , I am not able to reproduce the Error you're getting when you're not using a Prefix. Did you do it on a fresh installation? Was the DB already existing, or did you create a new one?

**Comment by RCheesley** [comment]
> Hi @RCheesley , I am not able to reproduce the Error you're getting when you're not using a Prefix. Did you do it on a fresh installation? Was the DB already existing, or did you create a new one?

Always from a fresh, empty database with the default DDEV setup using the commands I mentioned - what commands are you using at CLI? Maybe I made an error?

**Comment by rohitp19** [comment]
Test Results:

**With prefix**
Install via the UI ✅
Install via CLI ✅

**No prefix**
Install via the UI ✅
Install via CLI ❌

Before running test for each of above scenario we have cleared cache directory and deleted local.php using   
`rm -rf /var/www/html/var/cache/* && rm /var/www/html/app/config/local.php` 
We have also tried each on new database.

In case of cli without prefix we are getting error. Tried removing `--db_table_prefix` parameter and setting `--db_table_prefix ''`
below are the outputs:

**Passing --db_table_prefix  as empty string**
```
www-data@638549060c2b:~/html$ php bin/console mautic:install --db_port 3306 --db_host db --db_name test_community_5 --db_user root --db_password root --db_table_prefix '' https://mautic-community2.local/ --env=dev --admin_firstname=admin --admin_lastname=admin --admin_username=user --admin_email=email@domainc.com --admin_password=password
 // Clearing the cache for the dev environment with debug false                                                                                                                                                                              
 [OK] Cache for the "dev" environment (debug=false) was successfully cleared.                                           
                                                                                                                        
Mautic Install
==============
Parsing options and arguments...
0 - Checking installation requirements...
Ready to Install!
1 - Creating database...
1.1 - Creating schema...
11:07:14 ERROR     [mautic] SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_community_5.lead_fields' doesn't exist
1.2 - Loading fixtures...
2 - Creating admin user...
3 - Email configuration...
4 - Final steps...

================
Install complete
================
```

**Removing --db_table_prefix  parameter**
```
www-data@638549060c2b:~/html$ php bin/console mautic:install --db_port 3306 --db_host db --db_name test_community_2 --db_user root --db_password root-pass https://mautic-community2.local/ --env=dev --admin_firstname=admin --admin_lastname=admin --admin_username=user --admin_email=email@domainc.com --admin_password=password
 // Clearing the cache for the dev environment with debug false                                                                                                                                  
 [OK] Cache for the "dev" environment (debug=false) was successfully cleared.                                                                                                                                                            

Mautic Install
==============
Parsing options and arguments...
0 - Checking installation requirements...
Ready to Install!
1 - Creating database...
1.1 - Creating schema...
11:38:33 ERROR     [mautic] SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_community_2.lead_fields' doesn't exist
1.2 - Loading fixtures...
2 - Creating admin user...
3 - Email configuration...
4 - Final steps...

================
Install complete
================
```

Additional Info"
**PHP version:** PHP 7.4.6 (cli) (built: May 15 2020 12:54:14) ( NTS )
**MySQL version:** 8.0.23 MySQL Community Server - GPL

**Comment by rohitpavaskar** [comment]
Test Results:

**With prefix**
Install via the UI ✅
Install via CLI ✅

**No prefix**
Install via the UI ✅
Install via CLI ❌

Before running test for each of above scenario we have cleared cache directory and deleted local.php using   
`rm -rf /var/www/html/var/cache/* && rm /var/www/html/app/config/local.php` 
We have also tried each on new database.

In case of cli without prefix we are getting error. Tried removing `--db_table_prefix` parameter and setting `--db_table_prefix ''`
below are the outputs:

**Passing --db_table_prefix  as empty string**
```
www-data@638549060c2b:~/html$ php bin/console mautic:install --db_port 3306 --db_host db --db_name test_community_5 --db_user root --db_password root --db_table_prefix '' https://mautic-community2.local/ --env=dev --admin_firstname=admin --admin_lastname=admin --admin_username=user --admin_email=email@domainc.com --admin_password=password
 // Clearing the cache for the dev environment with debug false                                                                                                                                                                              
 [OK] Cache for the "dev" environment (debug=false) was successfully cleared.                                           
                                                                                                                        
Mautic Install
==============
Parsing options and arguments...
0 - Checking installation requirements...
Ready to Install!
1 - Creating database...
1.1 - Creating schema...
11:07:14 ERROR     [mautic] SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_community_5.lead_fields' doesn't exist
1.2 - Loading fixtures...
2 - Creating admin user...
3 - Email configuration...
4 - Final steps...

================
Install complete
================
```

**Removing --db_table_prefix  parameter**
```
www-data@638549060c2b:~/html$ php bin/console mautic:install --db_port 3306 --db_host db --db_name test_community_2 --db_user root --db_password root-pass https://mautic-community2.local/ --env=dev --admin_firstname=admin --admin_lastname=admin --admin_username=user --admin_email=email@domainc.com --admin_password=password
 // Clearing the cache for the dev environment with debug false                                                                                                                                  
 [OK] Cache for the "dev" environment (debug=false) was successfully cleared.                                                                                                                                                            

Mautic Install
==============
Parsing options and arguments...
0 - Checking installation requirements...
Ready to Install!
1 - Creating database...
1.1 - Creating schema...
11:38:33 ERROR     [mautic] SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test_community_2.lead_fields' doesn't exist
1.2 - Loading fixtures...
2 - Creating admin user...
3 - Email configuration...
4 - Final steps...

================
Install complete
================
```

Additional Info:
**PHP version:** PHP 7.4.6 (cli) (built: May 15 2020 12:54:14) ( NTS )
**MySQL version:** 8.0.23 MySQL Community Server - GPL

**Review by n-azimy — DISMISSED** [review]
I tried all 4 possible ways to install, with and without prefix, via CLI and GUI
Everything works for me know.

Test results:
With prefix
Install via the UI ✅
Install via CLI ✅

No prefix
Install via the UI ✅
Install via CLI ✅



Output for CLI installation without prefix:
```
bin/console mautic:install --mailer_from_name="DDEV" --mailer_from_email="mautic@ddev.local" --mailer_transport="smtp" --mailer_host="localhost" --mailer_port="1025" --db_driver="pdo_mysql" --db_host="localhost" --db_port="3306" --db_user="******" --db_password="******" --db_backup_tables="false" --admin_email="admin@mautic.local" --admin_password="mautic" https://mautic.ddev.site --env=dev --db_name="db_new" 

 // Clearing the cache for the dev environment with debug true                                                          

                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                                            
                                                                                                                        

Mautic Install
==============

Parsing options and arguments...
0 - Checking installation requirements...
Ready to Install!
1 - Creating database...
1.1 - Creating schema...
1.2 - Loading fixtures...
2 - Creating admin user...
3 - Email configuration...
4 - Final steps...

================
Install complete
================
```

**Comment by RCheesley** [comment]
@mabumusa1 @luguenth we seem to have a big load of tests failing on this PR now - can you please take a look?

**Comment by dennisameling** [comment]
OK I was able to reproduce the issue locally where tests fail if Mautic is not installed. It tries to redirect to `/index.php/installer` which is an indication that Mautic thinks it's not installed yet. After installing Mautic locally, the tests pass. The CI pipeline has an "Install Mautic" step so something must be going wrong there, because when running the tests, which comes right after that, Mautic still thinks that it's not installed yet. One possible cause I could think of is that this PR introduced a bug where it doesn't respect the `db_name`/`db_user`/etc. that we set in the CI pipeline, and installs into a different database instead (or something similar to this).

I'll have a closer look tomorrow by adding [tmate](https://github.com/marketplace/actions/debugging-with-tmate) to the CI pipeline, so I can log into the database and see in which database Mautic was actually installed

**Comment by dennisameling** [comment]
Created https://github.com/mautic/mautic/pull/10350 as a successor to this PR - it's up to date with the latest changes from the `features` branch and the tests are passing 🎉 therefore closing this one

**Comment by dennisameling** [comment]
For info - the tests in this PR were failing because of `define('MAUTIC_INSTALLER', 1)` - the thing here is that the constant is defined once during a PHPUnit test run, but then remains active in the rest of the tests as well. That's causing other, unrelated tests to fail as the logic thinks Mautic still has to be installed. https://github.com/mautic/mautic/pull/9934/commits/ed82bfeb5f71289ab75877d25a1454162d0728a9 prevents that by only defining `MAUTIC_INSTALLER` when we're not running tests (`IS_PHPUNIT`). CC @luguenth 

Reopened this PR in favor of #10350

**Comment by dennisameling** [comment]
This PR can now be tested again. Please make sure to test this in the following 4 scenarios:

- CLI installation with a DB prefix
- CLI installation without a DB prefix
- UI installation with a DB prefix
- UI installation without a DB prefix

To clean things up after testing each scenario, you can run `ddev delete --omit-snapshot && rm app/config/local.php && rm -rf var/cache && ddev start` to start with a clean state.

For CLI installation, simply run the DDEV command below:

```
ddev exec bin/console mautic:install --mailer_from_name="DDEV" --mailer_from_email="mautic@ddev.local" --mailer_transport="smtp" --mailer_host="localhost" --mailer_port="1025" --db_driver="pdo_mysql" --db_host="db" --db_port="3306" --db_name="db" --db_user="db" --db_password="db" --db_table_prefix="mau_" --db_backup_tables="false" --admin_email="admin@mautic.local" --admin_password="mautic" https://mautic.ddev.site --env=dev
```

For CLI installation without a prefix, simply leave out `--db_table_prefix`, so that it looks as follows:

```
ddev exec bin/console mautic:install --mailer_from_name="DDEV" --mailer_from_email="mautic@ddev.local" --mailer_transport="smtp" --mailer_host="localhost" --mailer_port="1025" --db_driver="pdo_mysql" --db_host="db" --db_port="3306" --db_name="db" --db_user="db" --db_password="db" --db_backup_tables="false" --admin_email="admin@mautic.local" --admin_password="mautic" https://mautic.ddev.site --env=dev
```

**Comment by mabumusa1** [comment]
I just tested the new fixes, it works as expected. Thanks @dennisameling

**Review by RCheesley — APPROVED** [review]
All four scenarios are now working flawlessly, a huuuuge thank you to everybody who has worked on getting this PR over the line!

Let's go! 🚀

File: app/bundles/InstallBundle/DependencyInjection/Compiler/InstallCommandPass.php [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+        );
+        $definition->addOption(
+            new InputOption(
+                '--env',
+                '-e',
+                InputOption::VALUE_REQUIRED,
+                'The Environment name.',
+                $container->getParameter('kernel.environment')
+            )
+        );
```
Comment (escopecz) [inline app/bundles/InstallBundle/DependencyInjection/Compiler/InstallCommandPass.php:35]: @mabumusa1 what was the reason the add the options here and not in the `InstallCommand` itself?

Comment (mabumusa1) [reply app/bundles/InstallBundle/DependencyInjection/Compiler/InstallCommandPass.php:35]: @escopecz I think we needed this to be injected before the cache warmup, otherwise, it will not be collected if inserted in the `InstallCommand`. I am not 100% sure. but I think this is the reason

Comment (escopecz) [reply app/bundles/InstallBundle/DependencyInjection/Compiler/InstallCommandPass.php:35]: Ok. That's one of the reasons why we need to cover the code with tests. A test would show us the need for it.

As the InstallCommand must have dependencies for Symfony 5 I had to simplify the code. I tested it by clearing the cache and then running the install command with a table prefix param and it is present in the compiler pass. See https://github.com/mautic/mautic/pull/11041/commits/3cabc82b523d47a825219d1c23f7c6c0fa010d34

Comment (mabumusa1) [reply app/bundles/InstallBundle/DependencyInjection/Compiler/InstallCommandPass.php:35]: I totally agree, this PR was not fully covered. Once I am done with the email PR I will work on increasing the coverage for this command
