### PR TITLE
[FIX] Added default value to avoid null value exception

### LINKED ISSUE #10231: Error in API Library tests relating to GrapesJS builder
## Bug Description
The API library tests have been failing since 25th June with the following error:

`Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuil...`

See full run details here: https://github.com/mautic/api-library/runs/2989055129?check_suite_focus=true

### PR DESCRIPTION
**Pull request by luguenth**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #10231 

This should fix the failing API-Tests. A default value for the function was missing

#### Steps to test this PR:

To test with the API Library:

Assuming you are using DDEV and GitHub CLI:

`gh repo fork mautic/api-library`

select ‘yes’ to clone locally

`cd api-library`
`ddev start`

Type 'yes' to have DDEV set up a Mautic instance to test against (this will be in /mautic in the api-library directory)

Then run `ddev exec composer test` to run the tests.  Modify this command to run a specific test, eg. `ddev exec 
 composer test -- --filter testCreateGetAndDelete tests/Api/NotesTest.php`.

Modify this command to run all tests in one class, eg. `ddev exec composer test -- --filter test tests/Api/NotesTest.php`

This step may take some time ... go get a ☕ !

Once you can reproduce the issue, apply the PR:

`cd mautic`
`gh pr checkout 10259`
`cd ..`
`ddev exec composer test`

Tests should now pass.

### CODE REVIEW

**Comment by RCheesley** [comment]
Please pull in the latest changes from features @luguenth - can't do it for you on a protected branch ;)

**Comment by RCheesley** [comment]
**Testing before applying the PR:**

```
ruth.cheesley@MacBookPro-RuthCheesley api-library % ddev exec composer test
> vendor/bin/paratest
Running phpunit in 8 processes with /var/www/html/vendor/phpunit/phpunit/phpunit

Configuration read from /var/www/html/phpunit.xml.dist

.....................S....FFFFFFF............S.................  63 / 304 ( 20%)
....F.....S......................FFFFF.........FFFFFFF.FF...... 126 / 304 ( 41%)
............................................................... 189 / 304 ( 62%)
....................F................................S....SS... 252 / 304 ( 82%)
.S..........................................F.......            304 / 304 (100%)

Time: 11:47.904, Memory: 6.00 MB

There were 24 failures:

1) Mautic\Tests\Api\EmailsTest::testGetListOfSpecificIds
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...
Payload: {
    "name": "test",
    "subject": "API test email",
    "customHtml": "<h1>Hi there!<\/h1>",
    "emailType": "list",
    "dynamicContent": [
        {
            "tokenName": "test content name",
            "content": "Some default <strong>content<\/strong>",
            "filters": [
                {
                    "content": "Variation 1",
                    "filters": []
                },
                {
                    "content": "Variation 2",
                    "filters": [
                        {
                            "glue": "and",
                            "field": "city",
                            "object": "lead",
                            "type": "text",
                            "filter": "Prague",
                            "display": null,
                            "operator": "="
                        },
                        {
                            "glue": "and",
                            "field": "email",
                            "object": "lead",
                            "type": "email",
                            "filter": "Prague",
                            "display": null,
                            "operator": "!empty"
                        }
                    ]
                }
            ]
        },
        {
            "tokenName": "test content name2",
            "content": "Some default <strong>content2<\/strong>",
            "filters": [
                {
                    "content": "Variation 3",
                    "filters": []
                },
                {
                    "content": "Variation 4",
                    "filters": [
                        {
                            "glue": "and",
                            "field": "city",
                            "object": "lead",
                            "type": "text",
                            "filter": "Raleigh",
                            "display": null,
                            "operator": "="
                        }
                    ]
                }
            ]
        }
    ],
    "lists": [
        2
    ]
}
Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MauticApiTestCase.php:178
/var/www/html/tests/Api/EmailsTest.php:113

2) Mautic\Tests\Api\EmailsTest::testCreateGetAndDelete
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MauticApiTestCase.php:104
/var/www/html/tests/Api/EmailsTest.php:123

3) Mautic\Tests\Api\EmailsTest::testEditPatch
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:148

4) Mautic\Tests\Api\EmailsTest::testEditPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:177

5) Mautic\Tests\Api\EmailsTest::testSendToSegment
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:215

6) Mautic\Tests\Api\EmailsTest::testSendToContact
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:252

7) Mautic\Tests\Api\EmailsTest::testBatchEndpoints
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MauticApiTestCase.php:104
/var/www/html/tests/Api/MauticApiTestCase.php:266
/var/www/html/tests/Api/EmailsTest.php:274

8) Mautic\Tests\Api\ContactFieldsTest::testGetList
The response has unexpected status code (500).

Response: {"errors":[{"message":"PHP Warning - require(\/var\/www\/html\/mautic\/var\/cache\/dev\/doctrine\/orm\/Proxies\/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: Operation not permitted","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/vendor\/doctrine\/common\/lib\/Doctrine\/Common\/Proxy\/AbstractProxyFactory.php","line":200,"args":[]},{"namespace":"Mautic\\CoreBundle\\ErrorHandler","short_class":"ErrorHandler","class":"Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler","type":"-\u003E","function":"handleError","file":"\/var\/www\/html\/mautic\/vendor\/doctrine\/common\/lib\/Doctrine\/Common\/Proxy\/AbstractProxyFactory.php","line":200,"args":[["integer",2],["string","PHP Warning - require(\/var\/www\/html\/mautic\/var\/cache\/dev\/doctrine\/orm\/Proxies\/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: Operation not permitted"],["string","\/var\/www\/html\/mautic\/ven...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MauticApiTestCase.php:146
/var/www/html/tests/Api/ContactFieldsTest.php:28
/var/www/html/tests/Api/MauticApiTestCase.php:212
/var/www/html/tests/Api/ContactFieldsTest.php:43

9) Mautic\Tests\Api\MessagesTest::testGetListOfSpecificIds
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:96

10) Mautic\Tests\Api\MessagesTest::testCreateGetAndDelete
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:103

11) Mautic\Tests\Api\MessagesTest::testEditPatch
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:110

12) Mautic\Tests\Api\MessagesTest::testEditPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:119

13) Mautic\Tests\Api\MessagesTest::testBatchEndpoints
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MauticApiTestCase.php:253
/var/www/html/tests/Api/MessagesTest.php:126

14) Mautic\Tests\Api\CampaignsTest::testGetListOfSpecificIds
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:211

15) Mautic\Tests\Api\CampaignsTest::testCreateGetAndDelete
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:218

16) Mautic\Tests\Api\CampaignsTest::testEditPatch
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:230

17) Mautic\Tests\Api\CampaignsTest::testEditPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:257

18) Mautic\Tests\Api\CampaignsTest::testAddAndRemove
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:264

19) Mautic\Tests\Api\CampaignsTest::testBatchEndpoints
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/MauticApiTestCase.php:253
/var/www/html/tests/Api/CampaignsTest.php:318

20) Mautic\Tests\Api\CampaignsTest::testEventAndSourceDeleteViaPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:323

21) Mautic\Tests\Api\CampaignsTest::testCampaignContactGetList
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:370

22) Mautic\Tests\Api\CampaignsTest::testCampaignContactEditEvent
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file":"\/var\/www...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:370
/var/www/html/tests/Api/CampaignsTest.php:424

23) Mautic\Tests\Api\SegmentsTest::testAddAndRemove
The response has unexpected status code (500).

Response: {"errors":[{"message":"PHP Warning - require(\/var\/www\/html\/mautic\/var\/cache\/dev\/doctrine\/orm\/Proxies\/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: Operation not permitted","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/vendor\/doctrine\/common\/lib\/Doctrine\/Common\/Proxy\/AbstractProxyFactory.php","line":200,"args":[]},{"namespace":"Mautic\\CoreBundle\\ErrorHandler","short_class":"ErrorHandler","class":"Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler","type":"-\u003E","function":"handleError","file":"\/var\/www\/html\/mautic\/vendor\/doctrine\/common\/lib\/Doctrine\/Common\/Proxy\/AbstractProxyFactory.php","line":200,"args":[["integer",2],["string","PHP Warning - require(\/var\/www\/html\/mautic\/var\/cache\/dev\/doctrine\/orm\/Proxies\/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: Operation not permitted"],["string","\/var\/www\/html\/mautic\/ven...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/SegmentsTest.php:151

24) Mautic\Tests\Api\StatsTest::testGetSimple
The response has unexpected status code (500).

Response: {"errors":[{"message":"PHP Notice - SessionHandler::gc(): ps_files_cleanup_dir: opendir(\/var\/lib\/php\/sessions) failed: Permission denied (13)","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/vendor\/symfony\/http-foundation\/Session\/Storage\/Handler\/StrictSessionHandler.php","line":101,"args":[]},{"namespace":"Mautic\\CoreBundle\\ErrorHandler","short_class":"ErrorHandler","class":"Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler","type":"-\u003E","function":"handleError","file":null,"line":null,"args":[["integer",8],["string","PHP Notice - SessionHandler::gc(): ps_files_cleanup_dir: opendir(\/var\/lib\/php\/sessions) failed: Permission denied (13)"],["string","\/var\/www\/html\/mautic\/vendor\/symfony\/http-foundation\/Session\/Storage\/Handler\/StrictSessionHandler.php"],["integer",101],["array",{"maxlifetime":["integer",1440]}]]},{"namespace":"","short_class":"SessionHandler","class":"SessionH...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/StatsTest.php:35
/var/www/html/tests/Api/StatsTest.php:112

FAILURES!
Tests: 304, Assertions: 4428, Failures: 24, Skipped: 7.

```

**After applying the PR:**

```
ruth.cheesley@MacBookPro-RuthCheesley api-library % ddev exec composer test
> vendor/bin/paratest
Running phpunit in 8 processes with /var/www/html/vendor/phpunit/phpunit/phpunit

Configuration read from /var/www/html/phpunit.xml.dist

.....................S...........FFFFFFF............S..........  63 / 304 ( 20%)
..........S......................FFFFF..FFFFFFF.FF............. 126 / 304 ( 41%)
............................................................... 189 / 304 ( 62%)
.....................................................S.SS....S. 252 / 304 ( 82%)
....................................................            304 / 304 (100%)

Time: 12:21.746, Memory: 6.00 MB

There were 21 failures:

1) Mautic\Tests\Api\EmailsTest::testGetListOfSpecificIds
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...
Payload: {
    "name": "test",
    "subject": "API test email",
    "customHtml": "<h1>Hi there!<\/h1>",
    "emailType": "list",
    "dynamicContent": [
        {
            "tokenName": "test content name",
            "content": "Some default <strong>content<\/strong>",
            "filters": [
                {
                    "content": "Variation 1",
                    "filters": []
                },
                {
                    "content": "Variation 2",
                    "filters": [
                        {
                            "glue": "and",
                            "field": "city",
                            "object": "lead",
                            "type": "text",
                            "filter": "Prague",
                            "display": null,
                            "operator": "="
                        },
                        {
                            "glue": "and",
                            "field": "email",
                            "object": "lead",
                            "type": "email",
                            "filter": "Prague",
                            "display": null,
                            "operator": "!empty"
                        }
                    ]
                }
            ]
        },
        {
            "tokenName": "test content name2",
            "content": "Some default <strong>content2<\/strong>",
            "filters": [
                {
                    "content": "Variation 3",
                    "filters": []
                },
                {
                    "content": "Variation 4",
                    "filters": [
                        {
                            "glue": "and",
                            "field": "city",
                            "object": "lead",
                            "type": "text",
                            "filter": "Raleigh",
                            "display": null,
                            "operator": "="
                        }
                    ]
                }
            ]
        }
    ],
    "lists": [
        49
    ]
}
Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MauticApiTestCase.php:178
/var/www/html/tests/Api/EmailsTest.php:113

2) Mautic\Tests\Api\EmailsTest::testCreateGetAndDelete
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MauticApiTestCase.php:104
/var/www/html/tests/Api/EmailsTest.php:123

3) Mautic\Tests\Api\EmailsTest::testEditPatch
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:148

4) Mautic\Tests\Api\EmailsTest::testEditPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:177

5) Mautic\Tests\Api\EmailsTest::testSendToSegment
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:215

6) Mautic\Tests\Api\EmailsTest::testSendToContact
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/EmailsTest.php:252

7) Mautic\Tests\Api\EmailsTest::testBatchEndpoints
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MauticApiTestCase.php:104
/var/www/html/tests/Api/MauticApiTestCase.php:266
/var/www/html/tests/Api/EmailsTest.php:274

8) Mautic\Tests\Api\MessagesTest::testGetListOfSpecificIds
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:96

9) Mautic\Tests\Api\MessagesTest::testCreateGetAndDelete
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:103

10) Mautic\Tests\Api\MessagesTest::testEditPatch
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:110

11) Mautic\Tests\Api\MessagesTest::testEditPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MessagesTest.php:119

12) Mautic\Tests\Api\MessagesTest::testBatchEndpoints
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/MessagesTest.php:57
/var/www/html/tests/Api/MauticApiTestCase.php:253
/var/www/html/tests/Api/MessagesTest.php:126

13) Mautic\Tests\Api\CampaignsTest::testGetListOfSpecificIds
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:211

14) Mautic\Tests\Api\CampaignsTest::testCreateGetAndDelete
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:218

15) Mautic\Tests\Api\CampaignsTest::testEditPatch
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:230

16) Mautic\Tests\Api\CampaignsTest::testEditPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:257

17) Mautic\Tests\Api\CampaignsTest::testAddAndRemove
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:264

18) Mautic\Tests\Api\CampaignsTest::testBatchEndpoints
The response has unexpected status code (500).

Response: {"errors":[{"message":"PHP Notice - SessionHandler::gc(): ps_files_cleanup_dir: opendir(\/var\/lib\/php\/sessions) failed: Permission denied (13)","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/vendor\/symfony\/http-foundation\/Session\/Storage\/Handler\/StrictSessionHandler.php","line":101,"args":[]},{"namespace":"Mautic\\CoreBundle\\ErrorHandler","short_class":"ErrorHandler","class":"Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler","type":"-\u003E","function":"handleError","file":null,"line":null,"args":[["integer",8],["string","PHP Notice - SessionHandler::gc(): ps_files_cleanup_dir: opendir(\/var\/lib\/php\/sessions) failed: Permission denied (13)"],["string","\/var\/www\/html\/mautic\/vendor\/symfony\/http-foundation\/Session\/Storage\/Handler\/StrictSessionHandler.php"],["integer",101],["array",{"maxlifetime":["integer",1440]}]]},{"namespace":"","short_class":"SessionHandler","class":"SessionH...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/MauticApiTestCase.php:253
/var/www/html/tests/Api/CampaignsTest.php:318

19) Mautic\Tests\Api\CampaignsTest::testEventAndSourceDeleteViaPut
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:323

20) Mautic\Tests\Api\CampaignsTest::testCampaignContactGetList
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:370

21) Mautic\Tests\Api\CampaignsTest::testCampaignContactEditEvent
The response has unexpected status code (500).

Response: {"errors":[{"message":"Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in \/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php on line 73","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/ArrayHelper.php","line":27,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"ArrayHelper","class":"Mautic\\CoreBundle\\Helper\\ArrayHelper","type":"::","function":"getValue","file":"\/var\/www\/html\/mautic\/plugins\/GrapesJsBuilderBundle\/Model\/GrapesJsBuilderModel.php","line":73,"args":[["string","customHtml"],["null",null],["array",[]]]},{"namespace":"MauticPlugin\\GrapesJsBuilderBundle\\Model","short_class":"GrapesJsBuilderModel","class":"MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel","type":"-\u003E","function":"addOrEditEntity","file...

Failed asserting that false is true.

/var/www/html/tests/Api/MauticApiTestCase.php:89
/var/www/html/tests/Api/CampaignsTest.php:185
/var/www/html/tests/Api/CampaignsTest.php:370
/var/www/html/tests/Api/CampaignsTest.php:424

FAILURES!
Tests: 304, Assertions: 4543, Failures: 21, Skipped: 7.

```

**Comment by RCheesley** [comment]
@kuzmany any ideas on this one?

File: plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php [hunk 1]
```diff
@@ -70,7 +70,7 @@ public function addOrEditEntity(Email $email)
 
         $this->getRepository()->saveEntity($grapesJsBuilder);
 
-        $customHtml = ArrayHelper::getValue('customHtml', $this->requestStack->getCurrentRequest()->get('emailform'));
+        $customHtml = ArrayHelper::getValue('customHtml', $this->requestStack->getCurrentRequest()->get('emailform'), []);
```
Comment (dennisameling) [inline plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php]: @luguenth the fix doesn't work because the `getValue()` function expects an array in the 2nd function argument, meaning that your fix (which adds a 3rd argument) unfortunately doesn't work in this case. The `get()` function on `getCurrentRequest()` also supports a default parameter, so the fix is to simply move the default value as can be seen below:

```suggestion
        $customHtml = ArrayHelper::getValue('customHtml', $this->requestStack->getCurrentRequest()->get('emailform', []));
```

Comment (luguenth) [reply plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php]: Ah I see :+1: Thanks!

**Review by dennisameling — COMMENTED** [review]
This PR partly fixes the issue, which is a great step already!

Without this PR, 22 failures: https://github.com/mautic/api-library/runs/3067840236
With this PR, 3 failures (new issues): https://github.com/mautic/api-library/runs/3067868603

The new issues that popped up now are:

```
There were 3 failures:

1) Mautic\Tests\Api\EmailsTest::testCreateGetAndDelete
>>> customHtml:
Failed asserting that '<h1>Hi there!</h1>' matches expected null.

/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:168
/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:139
/home/runner/work/api-library/api-library/tests/Api/EmailsTest.php:123

2) Mautic\Tests\Api\EmailsTest::testEditPut
>>> customHtml:
Failed asserting that '<h1>Hi there!</h1>' matches expected null.

/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:168
/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:139
/home/runner/work/api-library/api-library/tests/Api/EmailsTest.php:186

3) Mautic\Tests\Api\EmailsTest::testBatchEndpoints
>>> customHtml:
Failed asserting that '<h1>Hi there!</h1>' matches expected null.

/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:168
/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:129
/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:266
/home/runner/work/api-library/api-library/tests/Api/EmailsTest.php:274
```

Will have a look later to see what is causing this

**Review by dennisameling — APPROVED** [review]
While this doesn't fix all API library tests (but https://github.com/mautic/mautic/pull/10023 does), the code change is a welcome change as the default value of `null` doesn't work for the `ArrayHelper` (should be an array). 👍🏼

**Comment by kuzmany** [comment]
This was fixed by https://github.com/mautic/mautic/pull/10023

**Comment by npracht** [comment]
@luguenth can you please review https://github.com/mautic/mautic/pull/10023 as far as it has been brought before, we'll priorise this one.
Sorry for the extra work you've done we'll probably not use.

**Comment by luguenth** [comment]
Works flawlessly for me :) Don't mind about the other PR, I'm just happy for the release! :rocket:

**Comment by RCheesley** [comment]
@luguenth per the comments from @dennisameling this would be a good change to have even if it does not address the issue intended - can you please pull in the latest features branch so we can check the tests before considering for merging?

**Comment by luguenth** [comment]
up to date now :)
