### PR TITLE
FIX: Ignoring of custom option list for mapped fields (#14117)

### LINKED ISSUE #13306: Radio group in Forms doesn't respect properties
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I create a radio group in a form and select NO for "Use assigned contact/company field's list choices" with only one optionlist, I get the original fields anyway.
I suspect it happens for Checkbox group.
Sorry, my Mautic is in italian

### How can we reproduce this issue?

Step 1: Create a form with a Radio Group
Step 2: Map a field which has got some options in "Mapped Field" tab, for example "Title" field.
Step 3:  Select NO in Properties tab on "Use assigned contact/company field's list choices" and add only one option list item
Step 4: Click on save or update
Step 5: You get Mr, Mrs, Miss choices anyway

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### LINKED ISSUE #14441: Closed issue "When checkbox is mapped with custom boolean field, values ​​of the custom field are always written into the form" still exists in Mautic 5.2.x
### Mautic Series

5.2.x series

### Mautic installed version

5.2.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.27

### What browsers are you seeing the problem on?

_No response_

### What happened?

As already explained in the original post [See here #14225](https://github.com/mautic/mautic/issues/14225), I would like to continue (as it was standard in Mautic 4) to use for example in the case of a newsletter registration option in a contact form a single checkbox with a single label "I want the newsletter" and save this information in a custom contact field. However, if I map the checkbox group in the form with the boolean contact field, the options of the boolean field no/yes are displayed in the form and not the custom label (it is absolutely unusual to ask the form subscriber whether you want the newsletter, yes or no). The current workaround would be to use CSS to hide checkbox 1 "No" and overwrite the label of checkbox 2 "Yes" with custom content - but this is not possible for customers who use Mautic.

### How can we reproduce this issue?

Create in a form a checkbox group with custom label
image
which should be displayed in the form
image

to save this info in the contact, map checkbox with a boolean contact field, but do not use list options of this custom field
image

however, the result is that the contents of the contact field are displayed in the form and not the custom label
image

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by abhisekmazumdar**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #14441

## Description

See #14441 >> What happened? 

---
### 📋 Steps to test this PR:

1. Create a custom field of type Boolean, keeping all other options at their default settings.  
2. Next, create a form.  
3. Navigate to the Fields tab and add a Checkbox group.  
4. Assign a label to it.  
5. Go to the Mapped Field tab and link it to the newly created custom field.  
6. In the Properties tab, provide an Option list.  
7. Do not enable the "Use assigned contact/company field's list choices" toggle.  
8. Save the form and preview it. You will see that only the custom field options are displayed, not the Checkbox group Option list.

You can also checkout #14441 >> How can we reproduce this issue?

### CODE REVIEW

**Comment by abhisekmazumdar** [comment]
I should mention that although this was created in version 5.2, this issue also exists in version 6.x. Please address this when merging this PR.

**Review by shinde-rahul — APPROVED** [review]
The code changes look good.

Can we have the test case added to cover the scenario?

**Comment by escopecz** [comment]
@abhisekmazumdar I think the linked issue has wrong screenshot in the steps to replicate as it duplicates the one above it. It's also in german so I have trouble to understand what the problem is. Could you please write it again in the PR descroption with english examples?

**Comment by escopecz** [comment]
Also, would you be able to cover this with tests?

File: app/bundles/FormBundle/Tests/Entity/FieldTest.php [hunk 1]
```diff
@@ -328,4 +329,65 @@ public static function dataProvider(): iterable
         yield ['checkboxgrp', ['multiple' => 0], true];
         yield ['checkboxgrp', ['multiple' => 1], true];
     }
+
+    public function testCheckboxGroupOptionsWithCustomLeadFieldInForm(): void
```
Comment (abhisekmazumdar) [inline app/bundles/FormBundle/Tests/Entity/FieldTest.php]: Maybe this is not the right place. Please suggest a better location for this.

File: app/bundles/FormBundle/Tests/Entity/FieldTest.php [hunk 2]
```diff
@@ -328,4 +329,65 @@ public static function dataProvider(): iterable
...
+                'option2' => 'Second Option',
+            ],
+        ];
+        $field->setProperties($fieldProperties);
+
+        // Add field to form
+        $form->addField(0, $field);
+        $field->setForm($form);
+
+        // Verify the options
```
Comment (abhisekmazumdar) [inline app/bundles/FormBundle/Tests/Entity/FieldTest.php]: I know this is giving a false positive result. I want to check the rendering values, but I can't find a proper way to do it in the test. Please suggest the best approach I can take here.

File: app/bundles/FormBundle/Tests/Entity/FieldTest.php [hunk 3]
```diff
@@ -328,4 +329,65 @@ public static function dataProvider(): iterable
...
+
+        // Verify the field maintains its options when accessed through the form
+        $formField = $form->getFields()->getValues()[0];
+        $this->assertEquals(
+            ['option1' => 'First Option', 'option2' => 'Second Option'],
+            $formField->getProperties()['list']
+        );
+
+        // Verify the options are different from the mapped custom field
+        $this->assertNotEquals(
```
Comment (abhisekmazumdar) [inline app/bundles/FormBundle/Tests/Entity/FieldTest.php]: This part of the comparison is essential, but only if we can find a way to obtain the render value. Then we can simply pull the values from the objects.

File: app/bundles/FormBundle/Tests/Entity/FieldTest.php (hunk 1 above)
Comment (escopecz) [reply app/bundles/FormBundle/Tests/Entity/FieldTest.php]: I suggest to write a functional test. I'm not sure that this test is running the Twig file that you've modified. If you just create the entities, flush them with the EntityManager and then access the route where the change is visible then this would nicely test the issue the same way as end users would.

Check the examples of functional tests. Such tests are extending `MauticMysqlTestCase`

File: app/bundles/FormBundle/Tests/Controller/FormControllerFunctionalTest.php [hunk 4]
```diff
@@ -195,6 +196,49 @@ public function testMappedFieldIsNotAutoFilledWhenUpdatingField(): void
...
+            ],
+        ];
+        $field->setProperties($fieldProperties);
+        $field->setForm($form);
+        $this->em->persist($field);
+        $this->em->flush();
+        $this->em->clear();
+
+        $crawler = $this->client->request('GET', sprintf('/s/forms/edit/%d', $form->getId()));
+        $this->assertTrue($this->client->getResponse()->isOk());
```
Comment (escopecz) [inline app/bundles/FormBundle/Tests/Controller/FormControllerFunctionalTest.php]:
```suggestion
        $this->assertResponseIsSuccessful();
```

File: app/bundles/FormBundle/Tests/Controller/FormControllerFunctionalTest.php [hunk 5]
```diff
@@ -195,6 +196,49 @@ public function testMappedFieldIsNotAutoFilledWhenUpdatingField(): void
...
+
+        // Visit the form preview page
+        $crawler = $this->client->request('GET', sprintf('/s/forms/preview/%d', $form->getId()));
+        $this->assertTrue($this->client->getResponse()->isOk());
```
Comment (escopecz) [inline app/bundles/FormBundle/Tests/Controller/FormControllerFunctionalTest.php]:
```suggestion
        $this->assertResponseIsSuccessful();
```

**Review by escopecz — CHANGES_REQUESTED** [review]
What a nice test! Just a small suggestion that generates helpful debug info if the request fails.

**Comment by abhisekmazumdar** [comment]
Thanks, @escopecz, for your input; it made this possible. I believe this is ready for review now.

**Review by escopecz — APPROVED** [review]
Yes, this works! This is my checkbox:
Screenshot 2025-02-12 at 11 05 42
Before this change:
Screenshot 2025-02-12 at 11 05 33
Screenshot 2025-02-12 at 11 05 16
After this change:
Screenshot 2025-02-12 at 11 04 46
Screenshot 2025-02-12 at 11 04 38
