### PR TITLE
Fix segment mails not using site_url

### LINKED ISSUE #10137: Segment Mails do not use site_url (better version)
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This is a better and easier explanation of https://github.com/mautic/mautic/issues/10042 because previous issue was too confusing and difficult to reproduce.

The problem:
Mautic does not use `site_url` in trackable URL replacing when sending Segment Emails via UI. If I set `site_url` to `http://example.com` I expect all links in the emails to be replaced by Mautic and begin with `http://example.com`. When using Segment Emails the closest proxy URL is used instead.

In other words: I want to use different Mautic proxy so I can limit URLs available in public instance that accepts traffic from the internet(to track links etc.). To do this I have two proxies. One(links are changed) is `https://public.example.com` that is set as `site_url` and has allowed only access to tracking links. Other is `https://internal.example.com` which is available only in internal network. When I log in via `https://internal.example.com` and create campaigns, all links in email later begin with `https://public.example.com` which is correct. When I use Segment Emails however and sent them via UI, links in emails begin with `https://internal.example.com` instead which is not correct behaviour.

When debugging, I see that `$url` returned by router in https://github.com/mautic/mautic/blob/3.3/app/bundles/CoreBundle/Model/AbstractCommonModel.php#L248 contains wrong base URL.

| Q   | A
| --- | ---
| Mautic version | 3.2.4
| PHP version |  Docker base image php:7.3-apache
| Browser | Firefox

### Steps to reproduce
This can be also reproduced on localhost so here's a quick guide to do it locally:

 1. Install Mautic on localhost. Note the port. I am using port 8100 in this example.
 2. Install nginx if needed and put following server configuration to nginx:
```
server {
        listen 8877;

        location / {
                proxy_pass http://localhost:8100; #Assuming that your Mautic instance is on port 8100
                proxy_redirect off;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
       }
}
```
 3. Set `site_url` in Mautic to `http://localhost:8877`, it's the address of nginx proxy.
 4. Run Mailhog docker or any other application to get a "dummy" SMTP server to catch Mautic mails: `docker run --network host -it mailhog/mailhog`. Mailhog UI for checking emails will be accessible at `http://localhost:8025/`.
 5. Configure Mautic to use MailHog. `Other SMTP server`, address `localhost`, port `1025`. Set both SMTP encryption type and authentication mode to `None`.
 6. Log in to Mautic via original port, in my case it's `localhost:8100`. This is extremely important, do not use localhost:8877.
 7. Create any contact with any email(it does not matter because MailHog accepts everything), create a segment and add that contact to it.
 8. Create a campaign to the segment above with just `Send Email` step. Create email for that step, email needs to contain any link. Trigger that campaign and after emails are sent, check content in MailHog. All links in email should begin with `http://localhost:8877/...`
 9. Go to `Channels` and duplicate the email your created for the campaign but create it as `Segment Email`. Set target segment as the same that was used in previous Campaign.
 10. Sent that Segment Email by clicking `Send` in UI.
 11. Check that segment email in Mailhog. All urls in email will begin with `localhost:8100/...` which is incorrect because `site_url` is `localhost:8877`.
 
### Log errors

None available

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/99030122-segment-mails-do-not-use-site_url-better-version?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nick-vanpraet**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #10137 and #10042 

#### Description:

Based on https://github.com/mautic/mautic/pull/11492, plus test

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Change the site URL config to something else
3. Create a Segment
4. Create a Segment Email
5. Send the Segment Email
6. Check the email unsubscribe link. It should use the site_url instead of the current url you are on

### CODE REVIEW

**Comment by nick-vanpraet** [comment]
I'll fix the Rector, etc stuff momentarily but if someone can point me in the right direction for this test error:

`1) Mautic\EmailBundle\Tests\Model\EmailModelFunctionalTest::testSiteUrlAlwaysTakesPrecedenceWhenBuildingUrls
Symfony\Component\DependencyInjection\Exception\LogicException: Impossible to call set() on a frozen ParameterBag.`

That'd be much appreciated, so I don't spend too long looking for it. I'm not sure I can "fix" that, as the documentation says you can't change parameters after the container has been compiled. If anyone knows another way to set the site_url so the running process will also pick it up when calling `$this->coreParametersHelper->get('site_url')` that'd be great.

**Comment by nick-vanpraet** [comment]
Created backport PR for 4.x, noticed in 5.x $utmTags parameter is no longer part of buildUrl

https://github.com/mautic/mautic/pull/11920

**Comment by mollux** [comment]
@nick-vanpraet 

to fix the tests, you need to add the parameter to the `configParams` property, see [the `AbstractMauticTestCase` base class](https://github.com/mautic/mautic/blob/e162c39d8b10768e59685ea45ba977018dba5686/app/bundles/CoreBundle/Test/AbstractMauticTestCase.php#L39). 

This can be done by implementing the `::setUp()` method, and adding the config to the `configParams` list, and calling the parents `::setUp()` method afterrwards.
See an example[ in the `ConfigControllerFunctionalTest` class.](https://github.com/mautic/mautic/blob/e162c39d8b10768e59685ea45ba977018dba5686/app/bundles/ConfigBundle/Tests/Controller/ConfigControllerFunctionalTest.php#L27)

**Review by mabumusa1 — APPROVED** [review]
I tested this PR, it worked as expected. it has also automated tests.

File: app/bundles/EmailBundle/Tests/Model/EmailModelBuildUrlTest.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+    protected function setUp(): void
+    {
+        $this->configParams['site_url'] = 'https://foo.bar.com';
+        parent::setUp();
+    }
+
+    public function testSiteUrlAlwaysTakesPrecedenceWhenBuildingUrls(): void
+    {
+        /** @var EmailModel $emailModel */
+        $emailModel = self::$container->get('mautic.email.model.email');
```
Comment (escopecz) [inline app/bundles/EmailBundle/Tests/Model/EmailModelBuildUrlTest.php:21]: Just for next time, it's better to use the `assert` instead of type hints.
```suggestion
        $emailModel = self::$container->get('mautic.email.model.email');
        \assert($emailModel instanceof EmailModel)
```

**Review by escopecz — APPROVED** [review]
The code loos fine. Thanks! 👍
