### PR TITLE
Fix mautic#14245 Mautic doesn't show error when choosing remote provider

### LINKED ISSUE #14245: [UX] Mautic doesn't provide error message when selecting unavailable remote storage provider
### Mautic Series

5.1.x series

### Mautic installed version

5.x branch

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

Not relevant

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When creating a new Asset, you can select a remove storage for the file, then browse the files from this remote storage.
This process needs a previously set up plugin before starting to work, but if now you try to open the modal to browse the files selecting an unavailable provider, nothing happens in a production env (the dev env shows a PHP error).

It seems faulty, the user waits for something and nothing happens.

To fix the issue, we could have an error message.

### How can we reproduce this issue?

1. Go to Plugins
2. Click the button Install plugins
3. Go to Components > Assets
4. Create a new asset
5. In Storage location, select Remote
6. Click Browse Remote Files
7. Click Amazon S3
8. See the PHP error (dev env) or simply nothing (prod env)

image

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by PedroLoureiro1**
Discovered that it was necessary to validate client_id and client_secret configurations before proceeding. If they are missing, an exception is thrown and properly handled. Additionally, I implemented specific error messages to inform users about failures when loading files from the selected remote storage provider.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️ 
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ❌ 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #14245  

## Description

Mautic doesn't provide error when selecting unavailable provider Discovered that it was necessary to validate client_id and client_secret configurations before proceeding. If they are missing, an exception is thrown and properly handled. Additionally, I implemented specific error messages to inform users about failures when loading files from the selected remote storage provider

---
### 📋 Steps to test this PR:

1.Go to Plugins
2.Click the button Install plugins
3.Go to Components > Assets
4.Create a new asset
5.In Storage location, select Remote
6.Click Browse Remote Files
7.Click Amazon S3
8.See the PHP error message (dev env)

### CODE REVIEW

File: plugins/MauticCloudStorageBundle/EventListener/RemoteAssetBrowseSubscriber.php [hunk 1]
```diff
@@ -24,6 +24,10 @@ public function onAssetRemoteBrowse(Events\RemoteAssetBrowseEvent $event): void
         /** @var CloudStorageIntegration $integration */
         $integration = $event->getIntegration();
 
-        $event->setAdapter($integration->getAdapter());
+        try {
+            $event->setAdapter($integration->getAdapter());
+        } catch (\Exception $e) {
```
Comment (escopecz) [inline plugins/MauticCloudStorageBundle/EventListener/RemoteAssetBrowseSubscriber.php]: Let's throw and catch a specific exception. This could mask some other exception that we'd like to record in the logs with the stack trace.

**Review by escopecz — CHANGES_REQUESTED** [review]
I was able to replicate the issue:
Screenshot 2025-04-15 at 16 13 46
And this PR fixes it:
Screenshot 2025-04-15 at 16 16 18
I have one suggestion for the code changes.

File: plugins/MauticCloudStorageBundle/EventListener/RemoteAssetBrowseSubscriber.php (hunk 1 above)
Comment (PedroLoureiro1) [reply plugins/MauticCloudStorageBundle/EventListener/RemoteAssetBrowseSubscriber.php]: Hi @escopecz,

I’ve made changes to the `RemoteAssetBrowseSubscriber.php` to handle exceptions more specifically. Previously, a general exception was caught, which could potentially mask other important exceptions. I’ve now replaced this with the specific `InvalidCredentialConfigurationException` to ensure that other exceptions can still be logged properly with their stack traces.

Could you please review the changes and let me know if everything looks good? If you have any suggestions or concerns, feel free to share them.

Thanks in advance for your time!

Best regards,  
Pedro Loureiro

File: app/bundles/AssetBundle/Assets/js/asset.js [hunk 2]
```diff
@@ -28,7 +28,8 @@ Mautic.updateRemoteBrowser = function(provider, path) {
 
                 mQuery('.remote-file-search').quicksearch('#remoteFileBrowser .remote-file-list a');
             } else {
-                // TODO - Add error handler
+                const flashMessage = Mautic.addErrorFlashMessage(Mautic.translate('mautic.asset.update.remote.browser.error'));
+                Mautic.setFlashes(flashMessage);
```
Comment (escopecz) [inline app/bundles/AssetBundle/Assets/js/asset.js]: Can we use the error message from the flash message generated by the server instead of doing this in JS?

File: app/bundles/CoreBundle/Translations/en_US/javascript.ini [hunk 3]
```diff
@@ -18,4 +18,5 @@ mautic.core.tabs.more="more"
 mautic.core.copied="Copied to clipboard"
 mautic.core.request.error="Your request could not be processed, please try again"
 mautic.campaign.event.clone.success="Your event has been cloned. Select a node in this or another campaign to attach it."
-mautic.user.config.title.experience_and_learning.reset_confirmation="All dismissed resources visible again"
\ No newline at end of file
+mautic.user.config.title.experience_and_learning.reset_confirmation="All dismissed resources visible again"
+mautic.asset.update.remote.browser.error="Service selection failed. Please verify that your credentials are correctly configured."
```
Comment (escopecz) [inline app/bundles/CoreBundle/Translations/en_US/javascript.ini]: Because to separate the concerns, the CoreBundle shouldn't contain code specific for the AssetBundle.

**Review by escopecz — APPROVED** [review]
That's pretty much perfect!

File: app/bundles/CoreBundle/Translations/en_US/javascript.ini (hunk 3 above)
Comment (PedroLoureiro1) [reply app/bundles/CoreBundle/Translations/en_US/javascript.ini]: Hi @escopecz,

With this update, the error message now uses Mautic.addErrorFlashMessage together with Mautic.setFlashes, ensuring that the message is styled consistently with the rest of the application and properly dismissible by the user. Additionally, the response message from the backend is reused directly, without hardcoded fallback or translation strings.

Could you please review the changes and let me know if they align with the current UI standards and error handling practices in Mautic? I'm happy to make any adjustments you suggest.

Thanks in advance!

Best regards,
Pedro Loureiro

**Review by escopecz — APPROVED** [review]
Works like a charm. I see no more issues in the code 👍 
Screenshot 2025-04-29 at 12 54 05

**Comment by escopecz** [comment]
@all-contributors please add @PedroLoureiro1 for code
