### PR TITLE
Fix ampersand encoding in tokens

### LINKED ISSUE #11643: URL's used as email token are malformed
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you use an URL as a token in an email, it converts `&` to `&#38;`, breaking the URL. I can find [several](https://github.com/mautic/mautic/blob/5.x/app/bundles/PageBundle/Model/RedirectModel.php#L114-L117) [workarounds](https://github.com/mautic/mautic/blob/5.x/app/bundles/PageBundle/Model/TrackableModel.php#L118-L121) in the code that replace `&amp;` with `&` before it is inserted as tracking link, but these do not decode the decimal version.

API endpoint used: https://developer.mautic.org/?php#send-email-to-contact

Relevant code points:
 * https://github.com/mautic/mautic/blob/5.x/app/bundles/EmailBundle/Controller/Api/EmailApiController.php#L125
 * https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Helper/InputHelper.php#L193

Demo of extracted code that causes the issue: https://3v4l.org/c8rgB

### How can we reproduce this issue?

1. Make sure you have a contact;
2. Create a template email and use `{url}` as the URL of a link;
4. Call the API endpoint: `/api/emails/[ID OF EMAIL]/contact/[ID OF CONTACT]/send` with body:
```
{
    "tokens": {
        "url": "https://localhost/test?foo=bar&email=john.doe%40example.com"
    }
}
```
4. Click the link in the received email;
5. See you're redirected to `https://localhost/test?foo=bar&#38;email=john.doe%40example.com`.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JaZo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #11643 

#### Description:

This PR will make sure decimal or hex encoded ampersands are properly handled. As you can see in #11643, ampersands in tokens are replaced with `&#38;`. This is caused by [`InputHelper::clean`](https://github.com/mautic/mautic/blob/4.4/app/bundles/CoreBundle/Helper/InputHelper.php#L193). I don't feel really comfortable in changing that logic, so I extended the current 'decode ampersands' functionality to support decimal and hex encoded ampersands.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester));
2. Make sure you have a contact;
3. Create a template email and use `{url}` as the URL of a link;
4. Call the API endpoint: `/api/emails/[ID OF EMAIL]/contact/[ID OF CONTACT]/send` with body:
```
{
    "tokens": {
        "url": "https://localhost/test?foo=bar&email=john.doe%40example.com"
    }
}
```
5. Click the link in the received email;
6. See you're redirected to `https://localhost/test?foo=bar&email=john.doe%40example.com` instead of `https://localhost/test?foo=bar&#38;email=john.doe%40example.com`.

### CODE REVIEW

File: app/bundles/EmailBundle/Entity/Email.php [hunk 1]
```diff
@@ -1124,8 +1124,8 @@ private function decodeAmpersands(&$content)
             foreach ($matches[0] as $url) {
                 $newUrl = $url;
 
-                while (false !== strpos($newUrl, '&amp;')) {
-                    $newUrl = str_replace('&amp;', '&', $newUrl);
+                while (false !== strpos($newUrl, '&amp;') || false !== strpos($newUrl, '&#38;') || false !== strpos($newUrl, '&#x26;')) {
+                    $newUrl = str_replace(['&amp;', '&#38;', '&#x26;'], '&', $newUrl);
                 }
```
Comment (escopecz) [inline app/bundles/EmailBundle/Entity/Email.php]: I can see that you found this decoding to be done in multiple places and fixed it everywhere. That's great! How about to make the code a bit DRY-er and encapsulate it with a static method in the [UrlHelper](https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Helper/UrlHelper.php)?

This way it will be fairly easy to write unit tests for it.

**Review by escopecz — CHANGES_REQUESTED** [review]
> I couldn't find any existing tests for the ampersand decoding that I could extend, so currently this change isn't tested.

We have a rule that all new changes must be covered with tests. Even if the code is not covered with tests yet. That's how we want to improve the test coverage and over all stability of the system. We need to get out of the "fix one bug and create 2 new ones" cycle. And tests are the only way out.

Let me know if you need any help with the tests.

**Comment by escopecz** [comment]
One more thing. This is based against the 4.4 branch. Please create a duplicate PR against the 5.x branch. That must be merged first and then we can merge this and release it for Mautic 4 as well.

File: app/bundles/EmailBundle/Entity/Email.php (hunk 1 above)
Comment (JaZo) [reply app/bundles/EmailBundle/Entity/Email.php]: Better! I created the static method in the UrlHelper.

**Comment by JaZo** [comment]
Rebased and retargeted to 5.x and added tests!

**Review by escopecz — APPROVED** [review]
The code looks great. Thank you! 👍

**Review by volha-pivavarchyk — APPROVED** [review]
Works as described

image

image
