### PR TITLE
Fixing DoctrineEventSubscriber for plugin installations

### LINKED ISSUE #11186: In SchemaException.php line 34: [Doctrine\DBAL\Schema\SchemaException (10)]  There is no table with name 'mautic_leads' in the schema.
### Mautic Version

4.2.x series

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

M 4.3.1
When I tried install custom objects plugin I see this info:

```
In SchemaException.php line 34:
                                                                     
  [Doctrine\DBAL\Schema\SchemaException (10)]                        
  There is no table with name 'mautic_pr.pressleads' in the schema.  
                                                                     

Exception trace:
  at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:34
 Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:178
 Doctrine\DBAL\Schema\Schema->getTable() at /var/www/pr/app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php:28
 Mautic\InstallBundle\EventListener\DoctrineEventSubscriber->postGenerateSchema() at /var/www/pr/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:64
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:409
 Doctrine\ORM\Tools\SchemaTool->getSchemaFromMetadata() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:116
 Doctrine\ORM\Tools\SchemaTool->getCreateSchemaSql() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:47
 Mautic\PluginBundle\Bundle\PluginBundleBase::installPluginSchema() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:27
 Mautic\PluginBundle\Bundle\PluginBundleBase::onPluginInstall() at /var/www/pr/plugins/MauticRefreshSegmentButtonPluginBundle/MauticRefreshSegmentButtonPluginBundle.php:28
 MauticPlugin\MauticRefreshSegmentButtonPluginBundle\MauticRefreshSegmentButtonPluginBundle::onPluginInstall() at /var/www/pr/app/bundles/PluginBundle/Helper/ReloadHelper.php:133
 Mautic\PluginBundle\Helper\ReloadHelper->installPlugins() at /var/www/pr/app/bundles/PluginBundle/Facade/ReloadFacade.php:40
 Mautic\PluginBundle\Facade\ReloadFacade->reloadPlugins() at /var/www/pr/app/bundles/PluginBundle/Command/ReloadCommand.php:35
 Mautic\PluginBundle\Command\ReloadCommand->execute() at /var/www/pr/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/pr/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/pr/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/pr/bin/console:42

mautic:plugins:reload [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```
`
It looks similar to: https://github.com/mautic/mautic/issues/11163

### How can we reproduce this issue?

Step 1: Upload custom objects budle
Step 2: Run mautic:plugins:reload -vvv

### Relevant log output

```shell
In SchemaException.php line 34:
                                                                     
  [Doctrine\DBAL\Schema\SchemaException (10)]                        
  There is no table with name 'mautic_pr.pressleads' in the schema.  
                                                                     

Exception trace:
  at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:34
 Doctrine\DBAL\Schema\SchemaException::tableDoesNotExist() at /var/www/pr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:178
 Doctrine\DBAL\Schema\Schema->getTable() at /var/www/pr/app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php:28
 Mautic\InstallBundle\EventListener\DoctrineEventSubscriber->postGenerateSchema() at /var/www/pr/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:64
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:409
 Doctrine\ORM\Tools\SchemaTool->getSchemaFromMetadata() at /var/www/pr/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:116
 Doctrine\ORM\Tools\SchemaTool->getCreateSchemaSql() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:47
 Mautic\PluginBundle\Bundle\PluginBundleBase::installPluginSchema() at /var/www/pr/app/bundles/PluginBundle/Bundle/PluginBundleBase.php:27
 Mautic\PluginBundle\Bundle\PluginBundleBase::onPluginInstall() at /var/www/pr/plugins/MauticRefreshSegmentButtonPluginBundle/MauticRefreshSegmentButtonPluginBundle.php:28
 MauticPlugin\MauticRefreshSegmentButtonPluginBundle\MauticRefreshSegmentButtonPluginBundle::onPluginInstall() at /var/www/pr/app/bundles/PluginBundle/Helper/ReloadHelper.php:133
 Mautic\PluginBundle\Helper\ReloadHelper->installPlugins() at /var/www/pr/app/bundles/PluginBundle/Facade/ReloadFacade.php:40
 Mautic\PluginBundle\Facade\ReloadFacade->reloadPlugins() at /var/www/pr/app/bundles/PluginBundle/Command/ReloadCommand.php:35
 Mautic\PluginBundle\Command\ReloadCommand->execute() at /var/www/pr/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/pr/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/pr/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/pr/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/pr/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/pr/bin/console:42

mautic:plugins:reload [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/11186 , https://forum.mautic.org/t/how-to-install-acquias-custom-objects-plugin/24204/21

#### Description:

The change in https://github.com/mautic/mautic/pull/11059 causes troubles when installing plugins as the Schema contains only tables from the plugin. It does not contain the leads nor the companies tables. This PR is catching the exception if the table is not present and skips the additional logic.

#### Steps to test this PR:
1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Install some plugin that has some schema to install. For example https://github.com/acquia/mc-cs-plugin-custom-objects
3. When you run `bin/console mautic:plugins:install` you will get this error:
```
There is no table with name 'db.mautic_leads' in the schema.
```
which is fixed by this PR.

### CODE REVIEW

**Review by mollux — COMMENTED** [review]
I would test if the tables exists instead of depending on an error, but the suggested approach works

File: app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php [hunk 1]
```diff
@@ -18,13 +19,18 @@ public function getSubscribedEvents()
...
+        ];
 
         foreach ($fieldGroups as $tableName => $fields) {
-            $table = $schema->getTable(MAUTIC_TABLE_PREFIX.$tableName);
+            try {
+                $table = $args->getSchema()->getTable(MAUTIC_TABLE_PREFIX.$tableName);
+            } catch (SchemaException $e) {
+                // Ignore during plugin installations as not all tables are present in the schema.
+                continue;
+            }
```
Comment (escopecz) [inline app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php]: @mollux do you mean like this?
```suggestion
            $fullTableName = MAUTIC_TABLE_PREFIX.$tableName;
            if (!$args->getSchema()->hasTable($fullTableName)) {
                // Ignore during plugin installations as not all tables are present in the schema.
                continue;
            }
            $table = $args->getSchema()->getTable($fullTableName);
```
I was thinking about that but decided to do not introduce one more variable. Do you suggest that because throwing and catching the exception is a split millisecond slower than checking for the table?

Comment (mollux) [reply app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php]: No, not for the speed impact, more the eating up an error that could be useful. We know the exact conditions (table should exist), so we can check that. If an error is thrown, something else is wrong. Just my 2 cents :)

Comment (escopecz) [reply app/bundles/InstallBundle/EventListener/DoctrineEventSubscriber.php]: That makes total sense. I appreciate your $0.02! I'll commit the suggestion I made above.

File: app/bundles/InstallBundle/Tests/EventListener/DoctrineEventSubscriberTest.php [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+     */
+    private $entityManager;
+
+    protected function setUp(): void
+    {
+        parent::setUp();
+
+        $this->entityManager = $this->createMock(EntityManagerInterface::class);
+
+        defined('MAUTIC_TABLE_PREFIX') or define('MAUTIC_TABLE_PREFIX', '');
```
Comment (mollux) [inline app/bundles/InstallBundle/Tests/EventListener/DoctrineEventSubscriberTest.php:33]: I'll update https://github.com/mautic/mautic/pull/11196 once this is merged in, to remove this line again, but for now it's needed.

**Review by mollux — DISMISSED** [review]
yup, looks good now (apart form the CS issue)

**Comment by connectedbusiness-gary** [comment]
Working for me now! Thank you!
