### PR TITLE
Fix sent email point actions issues

### LINKED ISSUE #8603: Actions points on email not working with segment emails
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello, 
When you want to sent up an action point on email sent or email opened. you can't select segment email to filter on them.  Action are working on segment email but you can't filter on specific ones because of this.
| Q   | A
| --- | ---
| Mautic version | 2.16.1
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1.  Create a segment email, with a test segment and contact
2. Create an action point on email opening as in the screenshot below :
image
3. See in the limit to these selected mails that you can't find the mail you create before or any manual email
image

Thanks !

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
closes https://github.com/mautic/mautic/issues/8603
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8603
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Noticed few issues with sent emails point actions
1,  Noticed segment broadcast emails cannot be list in select box https://github.com/mautic/mautic/issues/8603
2, Noticed segment broadcast emails not trigger points action during the send email by web
3, Noticed email sent point action with enable repeatable, trigger point action  two times

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a segment email, with a test segment and contact
2. Create an action point on email opening as in the screenshot below :
image
3. See in the limit to these selected mails that you can't find the mail you create before or any manual email
image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps, see all emails in list

### CODE REVIEW

**Review by florentpetitjean — CHANGES_REQUESTED** [review]
Hello,
Just tested, works well except that the action **is sent an email**  doesn't seems to works with segment email : 
The action : 
image
Contact receive the email but no points triggered : 
image
Thanks

**Comment by kuzmany** [comment]
@florentpetitjean last commit should fixed it

**Review by florentpetitjean — CHANGES_REQUESTED** [review]
Test again : works except it triggered 2 time by action : 
image
Action is repeatable but shouldn't trigger twice for one email.
Thanks

**Comment by kuzmany** [comment]
Wait. But It couldn't be triggered twice times.

**Comment by kuzmany** [comment]
@florentpetitjean I found issue, please try now

**Review by florentpetitjean — DISMISSED** [review]
Works as intended now, Thanks !

**Comment by kuzmany** [comment]
@florentpetitjean sorry, I found another issue. I need figure out it in another way

**Comment by kuzmany** [comment]
@alanhartless there is any reason why  dispatchSendEvent() is dispatched two times for  EMAIL_ON_SEND? It make mess with point sent email action.

https://github.com/mautic/mautic/blob/2e79c963c15d03ae13f18c1eb96fdbf25b12e1ce/app/bundles/EmailBundle/Model/SendEmailToContact.php#L453

https://github.com/mautic/mautic/blob/f7c92f9f0324e76c1b1eb40347382c2fe94d1c84/app/bundles/EmailBundle/Helper/MailHelper.php#L382

It was added in this commit https://github.com/mautic/mautic/commit/6de334548073a16c6d81c7901cf0a26343c01298#diff-87a30e5e3c35f19b2b7e3fdc3f6578b0

**Review by florentpetitjean — APPROVED** [review]
Works fine now !
Thanks

**Comment by kuzmany** [comment]
Rebased

**Comment by npracht** [comment]
@florentpetitjean can you confirm here it works now rebased ?

**Review by florentpetitjean — DISMISSED** [review]
I confirmed it works after rebased

**Comment by RCheesley** [comment]
Set up as intended- was not able to select the email before but after applying the PR I could:

screenshot-local mautic3-2020 06 23-15_42_23

Contacts receive and read the email:

screenshot-local mautic3-2020 06 23-15_42_45

however no points are added:

screenshot-local mautic3-2020 06 23-15_43_43

@kuzmany maybe something changed with Mautic 3.0?

**Comment by kuzmany** [comment]
@RCheesley I've test it on mautibox and works for me https://mautibox.com/8619/s/contacts/view/55
Can you try look on my setup If copy yours?

**Comment by RCheesley** [comment]
One difference I can see:

screenshot-local mautic3-2020 06 25-18_45_45

**Comment by kuzmany** [comment]
@RCheesley works too. Were you logged it in Mautic? Can you try open it in incognito window?

**Comment by RCheesley** [comment]
Close & open for Scrutinizer

**Comment by dennisameling** [comment]
Moving to 3.0.2 milestone due to pending feedback

**Comment by kuzmany** [comment]
Based on my last comment we should remove pending feedback label.

**Comment by RCheesley** [comment]
Tested on 3.0.1 and working, points are being awarded as expected!

**Review by RCheesley — APPROVED** [review]

File: app/bundles/EmailBundle/EventListener/PointSubscriber.php [hunk 1]
```diff
@@ -115,12 +111,28 @@ public function onEmailOpen(EmailOpenEvent $event)
...
-        if ($leadArray = $event->getLead()) {
+        $leadArray = $event->getLead();
+        if ($leadArray && is_array($leadArray) && !empty($leadArray['id'])) {
             $lead = $this->entityManager->getReference(Lead::class, $leadArray['id']);
         } else {
             return;
         }
 
-        $this->pointModel->triggerAction('email.send', $event->getEmail(), null, $lead);
+        if ($this->shouldTriggerPointEmailSendAction($event, $lead)) {
```
Comment (escopecz) [inline app/bundles/EmailBundle/EventListener/PointSubscriber.php:121]: @kuzmany @dennisameling the issue of duplicated points was a bit higher. We called the event twice per email send. I discussed with @alanhartless that it was a bug. This commit fixes it so this check is not needed anymore.

https://github.com/mautic/mautic/pull/7716/commits/05bd59fa22494f861dc996e85f7a7ee7e83a89e0

Comment (kuzmany) [reply app/bundles/EmailBundle/EventListener/PointSubscriber.php:121]: Then this part we can remove, right?

Comment (escopecz) [reply app/bundles/EmailBundle/EventListener/PointSubscriber.php:121]: Yes. Maybe I can remove it as part of https://github.com/mautic/mautic/pull/7716 that is fixing the double event dispatch if you agree.

Comment (kuzmany) [reply app/bundles/EmailBundle/EventListener/PointSubscriber.php:121]: Yes, I've already seen it. Please do it as part of #7716 , then I'll make test.

Comment (escopecz) [reply app/bundles/EmailBundle/EventListener/PointSubscriber.php:121]: For the record, the code was removed as part of #7716
