### PR TITLE
Issue 8432 cookie php73

### LINKED ISSUE #8432: Samesite cookie fix not working in PHP 7.3 and higher
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
As reported by Lex Gabrees on Slack:

> So, I upgraded from 2.15.3 to 2.16beta in order to see if the samesite issue was fixed (which I was told) ... Now I get loads of PHP warnings about samesite and cookies. Does anyone know what these mean? See attachment ... Anyone know what these mean exactly (except that it's a samesite, cookie issue ofc)

The PR that is responsible for this is https://github.com/mautic/mautic/pull/8347.

After doing some research, I found that this only applies to PHP 7.3 and higher: https://stackoverflow.com/a/46971326

| Q   | A
| --- | ---
| Mautic version | 2.16.0-beta
| PHP version | 7.3
| Browser | N/A

### Steps to reproduce
1. For generating the errors as found below, you can use test with `curl` as described here: https://github.com/mautic/mautic/pull/8347#issuecomment-580336064
 
### Log errors
```
[2020-02-12 08:30:57] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3650,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 08:41:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3651,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 08:42:17] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3652,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 08:52:21] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3653,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 08:57:47] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3654,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:24] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3655,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_session_id","value":"","expire":1581493958,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_device_id","value":"2hjs4ec4msjfc84va5c3wmn","expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mtc_id","value":618,"expire":null,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mtc_sid","value":"2hjs4ec4msjfc84va5c3wmn","expire":null,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_session_id","value":"2hjs4ec4msjfc84va5c3wmn","expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"2hjs4ec4msjfc84va5c3wmn","value":618,"expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"2hjs4ec4msjfc84va5c3wmn","value":"","expire":1581493958,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_session_id","value":"","expire":1581493958,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_device_id","value":"1161arl2gbu3bhwp94fd2e5","expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mtc_id","value":396,"expire":null,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mtc_sid","value":"1161arl2gbu3bhwp94fd2e5","expire":null,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_session_id","value":"1161arl2gbu3bhwp94fd2e5","expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"1161arl2gbu3bhwp94fd2e5","value":396,"expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:38] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3656,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:40] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3657,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:42] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3658,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:44] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3659,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:49] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3660,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:53] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3661,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 09:52:55] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3662,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:18] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3663,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:29] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_session_id","value":"","expire":1581496109,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:29] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_device_id","value":"0fcy5wgzmfikp4b0vthjhs4","expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:29] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mtc_id","value":619,"expire":null,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:29] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mtc_sid","value":"0fcy5wgzmfikp4b0vthjhs4","expire":null,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:29] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_session_id","value":"0fcy5wgzmfikp4b0vthjhs4","expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:29] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"0fcy5wgzmfikp4b0vthjhs4","value":619,"expire":31536000,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
[2020-02-12 10:28:31] mautic.WARNING: PHP Warning - Cookie paths cannot contain any of the following ',; \t\r\n\013\014' - in file /var/www/mc.lexgabrees.com/htdocs/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 93 {"name":"mautic_referer_id","value":3664,"expire":1800,"path":null,"domain":null,"secure":null,"httponly":null,"sameSiteNoneText":"; samesite=none"} []
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by lukassykora**
**Please be sure you are submitting this against the _staging_ branch.**

Closes #8432 

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Support for PHP 7.3
| Automated tests included? | Tested by CookieHelperTest
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8432
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
PHP 7.3 handles samesite in different way in setcookie function.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Switch to PHP 7.3
2. Run test and you should get warnings.

#### Steps to test this PR:
1. No warning for PHP 7.3
2. Cookies are sent and have secure and samesitee=None

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

File: app/bundles/CoreBundle/Helper/CookieHelper.php [hunk 1]
```diff
@@ -79,19 +80,36 @@ public function setCookie($name, $value, $expire = 1800, $path = null, $domain =
...
+                [
+                    'samesite' => $sameSiteNoneTextGreaterPhp73
+                ]
+            );
+        } else {
+            setcookie(
+                $name,
+                $value,
+                ($expire) ? (int) (time() + $expire) : null,
+                (($path == null) ? $this->path : $path),
```
Comment (dennisameling) [inline app/bundles/CoreBundle/Helper/CookieHelper.php]: Shouldn't the `.$sameSiteNoneText` be here instead of in line 94? 😊

Comment (dennisameling) [reply app/bundles/CoreBundle/Helper/CookieHelper.php]: Also, could you please have a look at PHPCS as it's failing now? Thanks 😃

**Comment by dennisameling** [comment]
Steps to test:

- Get Chrome 80 or later
- Enable the new SameSite behavior as mentioned here: https://www.chromium.org/updates/same-site/test-debug#TOC-Enable-the-new-SameSite-behavior
- Check out this PR locally and install Mautic (e.g. at https://mautic.local).
- Create an HTML file on a different domain (e.g. https://mydomain.local):
```HTML
<!doctype html>
<html>
    <head>
        <script>
            (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
                w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
                m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://mautic.local/mtc.js','mt');
        
            mt('send', 'pageview');
        </script>
    </head>
</html>
```
- Open  your browser console in Chrome (Developer Tools > Console)
- Open your HTML file in Chrome (`https://mydomain.local/myfile.html`)

On an instance with Mautic 2.15.3, this results in the following console warning:

image

On an instance with the PR you just checked out, you should **not** get this warning message.

In my testing this worked with both PHP 7.2 and 7.3.
