### PR TITLE
Enforce pdo_mysql as doctrine driver as it's the only supported one

### LINKED ISSUE #13186: Mautic 5.0.0 installation issue
### Mautic Version

5.0.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

Hello ,

I was in the process of manual installation of Mautic 5.0.0 on AlmaLinux release 8.9, PHP 8.0.30, Apache 2.4, MYSQL 5.7.42 downloaded from : 
https://github.com/mautic/mautic/releases/download/5.0.0/5.0.0.zip

However after entering the database details i.e : 

image

Following error is thrown i.e : 

image

On checking log under /var/logs/ , error is thrown as below in 'Relevant log output' section : 

(Log is mentioned in log section). Please check.

What could be the issue ?. Could you please replicate this at your end ?.

### How can we reproduce this issue?

Step 1: Try to install mautic
Step 2: Enter database details and click on next . above error occurs. 

### Relevant log output

```shell
[2024-01-10 07:53:34] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception: "An exception occurred while establishing a connection to figure out your platform version. You can circumvent this by setting a 'server_version' configuration value  For further information have a look at: https://github.com/doctrine/DoctrineBundle/issues/673" at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/doctrine-bundle/ConnectionFactory.php line 133 {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): An exception occurred while establishing a connection to figure out your platform version.\nYou can circumvent this by setting a 'server_version' configuration value\n\nFor further information have a look at:\nhttps://github.com/doctrine/DoctrineBundle/issues/673 at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:133, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: Failed to set option 17 with value \"1\" at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:117, Doctrine\\DBAL\\Driver\\Mysqli\\Exception\\InvalidOption(code: 0): Failed to set option 17 with value \"1\" at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/dbal/src/Driver/Mysqli/Exception/InvalidOption.php:21)"} {"hostname":"{{DOMAIN-NAME}}","pid":2706588}
[2024-01-10 07:53:34] mautic.CRITICAL: Exception thrown when handling an exception (Doctrine\DBAL\Exception: An exception occurred while establishing a connection to figure out your platform version. You can circumvent this by setting a 'server_version' configuration value  For further information have a look at: https://github.com/doctrine/DoctrineBundle/issues/673 at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/doctrine-bundle/ConnectionFactory.php line 133) {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): An exception occurred while establishing a connection to figure out your platform version.\nYou can circumvent this by setting a 'server_version' configuration value\n\nFor further information have a look at:\nhttps://github.com/doctrine/DoctrineBundle/issues/673 at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:133, Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in the driver: Failed to set option 17 with value \"1\" at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:117, Doctrine\\DBAL\\Driver\\Mysqli\\Exception\\InvalidOption(code: 0): Failed to set option 17 with value \"1\" at /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/dbal/src/Driver/Mysqli/Exception/InvalidOption.php:21)"} {"hostname":"{{DOMAIN-NAME}}","pid":2706588}
[2024-01-10 07:53:34] mautic.WARNING: PHP Warning - Undefined variable $projectRoot - in file /{{PATH}}/{{TO}}/{{MAUTIC}}/app/config/paths.php - at line 15 [] {"hostname":"{{DOMAIN-NAME}}","pid":2706588}
[2024-01-10 07:53:35] mautic.ERROR: Doctrine\DBAL\Exception: An exception occurred while establishing a connection to figure out your platform version. You can circumvent this by setting a 'server_version' configuration value  For further information have a look at: https://github.com/doctrine/DoctrineBundle/issues/673 - in file /{{PATH}}/{{TO}}/{{MAUTIC}}/vendor/doctrine/doctrine-bundle/ConnectionFactory.php - at line 133 [] {"hostname":"{{DOMAIN-NAME}}","pid":2706588}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #13186 

#### Description:

This PR:
* requires `pdo` in `composer.json`
* checks during a compilerpass if `pdo_mysql` is an available driver, and throws an error if not
* removes the mysqli option from the installer
* hardcodes the `pdo_mysql` driver when pressing the local parameters
* shows a comprehensive error on CLI and web to explain what's going on

Screenshot 2024-01-12 at 17 29 25

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

File: app/bundles/CoreBundle/Loader/ParameterLoader.php [hunk 1]
```diff
@@ -178,6 +178,10 @@ private function loadLocalParameters(): void
             $compiledParameters = array_merge($compiledParameters, json_decode($envParameters, true));
         }
 
+        // Hardcode the dv_driver to pdo_mysql, as it is currently the only supported driver.
```
Comment (escopecz) [inline app/bundles/CoreBundle/Loader/ParameterLoader.php]:
```suggestion
        // Hardcode the db_driver to pdo_mysql, as it is currently the only supported driver.
```

File: app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php [hunk 2]
```diff
@@ -290,6 +292,10 @@ public static function prepareExceptionForOutput($exception)
             $trace             = $exception->getTrace();
             $context           = (method_exists($exception, 'getContext')) ? $exception->getContext() : [];
 
+            if ($originalException instanceof MessageOnlyErrorHandlerException) {
+                $file = $trace = $context = $line = '';
+            }
```
Comment (escopecz) [inline app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php]: What is this for?

**Review by escopecz — COMMENTED** [review]
I tested that the `db_driver` config option has no effect now. No matter what value I put there, Mautic always work. I also checked how the installation UI looks like:
Screenshot 2024-01-12 at 19 06 33
The select is still there but has only one pre-selected option. I guess we can remove that select later when we'll run on PDO-only driver for some time and we'll be sure it's not necessary to support more. Manual testing went good 👍

File: app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php (hunk 2 above)
Comment (mollux) [reply app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php]: to ensure the message doesn't look like this, as the file, line and stracktrace aren't relevant for this kind of message IMO

Screenshot 2024-01-12 at 19 21 31

Comment (escopecz) [reply app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php]: This will show up only if you have env=dev. In production there will be only the "Uh oh" message, right?

Comment (mollux) [reply app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php]: no, as it's an error before Mautic is even "booted" it's this kind over error, also in prod mode

Comment (mollux) [reply app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php]: that makes me wonder: why does the stacktrace show up in the first place in prod mode? I'll check again, as it shouldn't by default

**Review by escopecz — APPROVED** [review]
It will check if PDO is present during cache build and if not, it will show a handy message. Looks good. Thank you, Mattias! 👍
