### PR TITLE
Doctrine fixtures will load form DDL before executing inserts.

### LINKED ISSUE #11611: Error on loading Doctrine fixtures
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I am loading fixtures I am seeing this at the end of the process - it seems to load in the fixtures though. From @mollux : probably mixing DDL and DQL queries in the same request, together with PHP 8
 see https://github.com/mautic/mautic/pull/11059 for context.

```
loading [10] Mautic\AssetBundle\DataFixtures\ORM\LoadAssetData
 loading [10] MauticPlugin\MauticCitrixBundle\Tests\DataFixtures\ORM\LoadCitrixData

In Connection.php line 1854:
                                  
  There is no active transaction  
                                  

doctrine:fixtures:load [--append] [--group GROUP] [--em EM] [--purger PURGER] [--purge-exclusions PURGE-EXCLUSIONS] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Failed to execute command bin/console d:f:l: exit status 1
```

### How can we reproduce this issue?

Step 1: Install Mautic
Step 2: Load sample data using ddev exec bin/console d:f:l
Step 3: Note the error thrown

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Issue(s) addressed                     | Fixes #11611  

#### Description:
Load fixtures DDL before executing fixtures loading.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Load fixtures with `ddev exec bin/console d:f:l`

### CODE REVIEW

**Review by volha-pivavarchyk — APPROVED** [review]
Works well.

on the current branch:
image

on 5.x:
image

**Review by RCheesley — APPROVED** [review]
Thanks for fixing this issue @biozshock - Fixtures loaded perfectly without any errors! 

LGTM 🚀

File: app/bundles/CoreBundle/Doctrine/Common/DataFixtures/Event/PreExecuteEvent.php [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+use Doctrine\Common\DataFixtures\Purger\ORMPurger;
+use Doctrine\ORM\EntityManagerInterface;
+use Symfony\Contracts\EventDispatcher\Event;
+
+class PreExecuteEvent extends Event
+{
+    private EntityManagerInterface $entityManager;
+    private int $purgeMode;
+
+    public function __construct(EntityManagerInterface $entityManager, int $purgeMode)
```
Comment (escopecz) [inline app/bundles/CoreBundle/Doctrine/Common/DataFixtures/Event/PreExecuteEvent.php:16]: I'm not a big fan of adding services to the events. We have that in some events and it's hard to maintain. The subscriber that is listening for this event should have the EntityManager as a dependency.

Comment (biozshock) [reply app/bundles/CoreBundle/Doctrine/Common/DataFixtures/Event/PreExecuteEvent.php:16]: @escopecz I tend to do the same. EntityManager is in the event, because DI doesn't know which is passed here: https://github.com/mautic/mautic/pull/11701/files#diff-cbc1d88e43db02bb48a776328bd26d51e8e5549ba0deac052013d9d0344ed088R31

Comment (escopecz) [reply app/bundles/CoreBundle/Doctrine/Common/DataFixtures/Event/PreExecuteEvent.php:16]: I still don't get it. Passing Entity Manager [here](https://github.com/mautic/mautic/pull/11701/files#diff-c6fbb3dc5b1b873b78373a48784cbf8f1f81954bc517b3dfe8b93784300836ecR53) wouldn't work?

Comment (biozshock) [reply app/bundles/CoreBundle/Doctrine/Common/DataFixtures/Event/PreExecuteEvent.php:16]: No, because the DI can pass only one entity manager at DI compile time, while the entity manager used in command is passed at runtime time.

Comment (escopecz) [reply app/bundles/CoreBundle/Doctrine/Common/DataFixtures/Event/PreExecuteEvent.php:16]: Ok then. Let's go with this if there is no other wa. Thanks!
