### PR TITLE
Fixing redirects with ct param

### LINKED ISSUE #15152: Uncaught TypeError in PageModel leads to 500 error when processing invalid 'ct' tracking parameter
### Mautic Series

6.0.x series

### Mautic installed version

6.0.2

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.0

### What browsers are you seeing the problem on?

_No response_

### What happened?

**Bug Description**
In a production environment (APP_ENV=prod), a malformed or truncated ct (clickthrough) parameter in a tracking URL (/r/{redirectId}) causes an unhandled exception, resulting in a 500 Internal Server Error.
This happens in two stages:
The unserialize() function in CoreBundle/Helper/Serializer.php fails because the decoded ct value is not a valid serialized string. In a production environment, this E_NOTICE is promoted to an ErrorException.
While PageBundle/Controller/PublicController.php attempts to catch this, the subsequent code path inside PageModel::hitPage() is not resilient enough. The failed unserialize operation results in $query['ct'] becoming false. The code then attempts to call array_key_exists() on this boolean value, which triggers a fatal TypeError.
This makes tracking links fragile, as any corruption in the ct parameter can break the redirect entirely instead of being handled gracefully.

**Proposed Solution**
The fix requires making the code more resilient in two key places.
1. Catch the ErrorException in PublicController
Ensure the catch block in redirectAction can handle the ErrorException promoted from the unserialize() notice.
File: app/bundles/PageBundle/Controller/PublicController.php

```
- } catch (InvalidDecodedStringException $e) {
+ } catch (InvalidDecodedStringException|\ErrorException $e) {
      // Invalid ct value so we must unset it
      // and process the request without it
```
**2. Add a defensive check in PageModel**
Add an is_array() check in hitPage() to ensure $query['ct'] is a valid array before attempting to access its keys. This prevents the TypeError and provides a more robust fix.
File: app/bundles/PageBundle/Model/PageModel.php
```
- if (array_key_exists('ct', $query) && array_key_exists('email', $query['ct']) && array_key_exists('stat', $query['ct'])) {
+ if (array_key_exists('ct', $query) && is_array($query['ct']) && array_key_exists('email', $query['ct']) && array_key_exists('stat', $query['ct'])) {
      /** @var Stat $stat */
      $stat = $this->statRepository->findOneBy(['trackingHash' => $query['ct']['stat']]);
```
These changes together ensure that malformed tracking links are handled gracefully without crashing the application, allowing the redirect to proceed and logging the error correctly.

### How can we reproduce this issue?

Steps to Reproduce
1. Set up a Mautic instance in a production environment.
2. Create any tracked link that uses a redirect (e.g., a link in an email).
3. Access the redirect URL but provide a malformed/truncated ct parameter. For example, use a valid ct string and remove a few characters from the end.
Example URL: https://your-mautic.com/r/someRedirectId?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6MTt9czo1OiJlbWFpbCI7aToxO3M6ND (This is an example of an invalid string).
4. Observe the 500 Internal Server Error.
5.Check the Mautic production log for the TypeError.

### Relevant log output

```shell
[01-Jul-2025 15:05:13 Asia/Ho_Chi_Minh] PHP Notice:  unserialize(): Error at offset 109 of 109 bytes in /path/to/mautic/app/bundles/CoreBundle/Helper/Serializer.php on line 27

[2025-07-01T08:05:13.098098+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "array_key_exists(): Argument #2 ($array) must be of type array, bool given" at /path/to/mautic/app/bundles/PageBundle/Model/PageModel.php line 398 {"exception":"[object] (TypeError(code: 0): array_key_exists(): Argument #2 ($array) must be of type array, bool given at /path/to/mautic/app/bundles/PageBundle/Model/PageModel.php:398)
[stacktrace]
#0 /path/to/mautic/app/bundles/PageBundle/Model/PageModel.php(398): array_key_exists()
#1 /path/to/mautic/app/bundles/PageBundle/Controller/PublicController.php(527): Mautic\\PageBundle\\Model\\PageModel->hitPage()
#2 /path/to/mautic/vendor/symfony/http-kernel/HttpKernel.php(181): Mautic\\PageBundle\\Controller\\PublicController->redirectAction()
#3 ...
"}
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by biozshock**
When click-trough parmater is malformed, Mautic should handle it.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️ 
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ✔️ 
| Issue(s) addressed                     | Fixes #15152 #14272  

## Description
Fix for the related issue.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Make sure you are using the prod env.
3. Create any tracked link that uses a redirect (e.g., a link in an email).
4. Access the redirect URL but provide a malformed/truncated ct parameter. For example, use a valid ct string and remove a few characters from the end. Example URL: https://your-mautic.com/r/someRedirectId?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6MTt9czo1OiJlbWFpbCI7aToxO3M6ND (This is an example of an invalid string).
5. Observe Mautic properly redirects.

### CODE REVIEW

File: app/bundles/PageBundle/Tests/Controller/PageControllerSqlRollbackFunctionalTest.php [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+        $ct = [
+            'source'  => ['email', $email->getId()],
+            'email'   => $email->getId(),
+            'stat'    => $statHash,
+            'lead'    => '1',
+            'channel' => ['email' => $email->getId()],
+        ];
+        $encodedCt = base64_encode(serialize($ct));
+
+        $this->setUpSymfony();
```
Comment (patrykgruszka) [inline app/bundles/PageBundle/Tests/Controller/PageControllerSqlRollbackFunctionalTest.php]: This line probably breakes the GitHub CI, not sure why. 

Without this, the lead is recognized as an admin in M7, if I remember correctly. I couldn't get it to work properly, so I only left the `testThatInvalidClickThroughGetsProcessed()` test.

**Review by patrykgruszka — CHANGES_REQUESTED** [review]
The CI needs fixes, but the functionality is working fine. 

It fixes the malformed `ct` params and removes it before redirecting to destination page.

File: app/bundles/PageBundle/Tests/Controller/PageControllerSqlRollbackFunctionalTest.php (hunk 1 above)
Comment (biozshock) [reply app/bundles/PageBundle/Tests/Controller/PageControllerSqlRollbackFunctionalTest.php]: @patrykgruszka see the working test :)

**Comment by biozshock** [comment]
@kuzmany @RCheesley , should this one be also rebased on 7.0?

**Comment by matbcvo** [comment]
@biozshock, yes, could you please rebase this PR onto the 7.0 branch?

**Comment by biozshock** [comment]
@matbcvo Done!

**Comment by matbcvo** [comment]
@biozshock, I think something went wrong with the rebase - the code changes don't seem to be related to this PR.

**Comment by biozshock** [comment]
@matbcvo should be fine now.

**Review by patrykgruszka — APPROVED** [review]
Looks good  :+1:

**Review by escopecz — APPROVED** [review]
